### ISSUE TITLE
Custom delimiters

### ISSUE THREAD

**Issue by Mrhyuan** [fenom-template/fenom#113]
Any possible to use user-defined delimiters instead of default values('{', '}')? Thanks.

**Comment by pun-ky** [comment]
+1 because I'd like to sometimes embed JS in my code configuration generated by back-end...
To easy fix that problem maybe just replace default delimiter '{' with '{{' ? :)

```
<script type="text/javascript">
APP.config = {
    someKey: '{Settings::read('someKey')}'
};
</script>
```

**Comment by maxicms** [comment]
This code should work without using the tag {ignore}

**Comment by bzick** [comment]
Indeed. It's should work.
