### ISSUE TITLE
Модификатор truncate

### ISSUE THREAD

**Issue by alexandr-v** [fenom-template/fenom#116]
Параметр by_words = true работает неправильно.

в методе модификатора в регулярном выражении есть ошибка, должно быть:
```php
if ($by_words) {
    return preg_replace('#\s\S*$#usS', "", $match[1]) . $etc;
} else {
...
```
регулярное вырожение для случая $middle = true и $by_words = true скорее всего тоже неправильное, я не разбирался... 

извиняюсь что сам не поправил)) не успеваю...

**Comment by bzick** [comment]
На каком тексте и с какими параметрам у Вас работает не правильно truncate?

**Comment by alexandr-v** [comment]
Пример:
```html
{'aaaa bbb cccc ddd eeeeee ffff'|truncate:15:"...":true}
```
должно получиться: aaaa bbb cccc... 
в реальности - aaaa...

из-за того что в '#\s.*$#usS' стоит . (любой символ), а должен быть не пробельный символ, т.е. \S
