### ISSUE TITLE
Множественная проверка наличия функции в кешированном  шаблоне

### ISSUE THREAD

**Issue by maxicms** [fenom-template/fenom#137]
вот пример кода который скорее всего не совсем правильный так как одна и таже функци проверяется n-ое количество раз, и равно кол-ву вызывов в шаблоне.
<?php 
/** Fenom template 'index.tpl' compiled at 2015-01-22 16:15:31 */
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_printBody')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.printBody.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}
if (!is_callable('fenom_function_template_dir')) {
	include_once 'C:\OpenServer\domains\myinstantcms\vendor\fenom/Plugins\function.template_dir.php';
}

return new Fenom\Render($fenom, function ($var, $tpl) {
?><!DOCTYPE html>

**Comment by bzick** [comment]
Ой, бага. Поправлю
