### ISSUE TITLE
Проблема с опцией auto_strip

### ISSUE THREAD

**Issue by maxicms** [fenom-template/fenom#140]
После последнего обновления перестала работать данная опция, при ее включении шаблон вообще не генерируется при этом ошибок выполенния нет.

**Comment by Sleuthhound** [comment]
Странно, у меня вроде все работает. Пробовал так
```php
$fenom->setOptions(array("strip" => true));
```
и так
```
$fenom->setOptions(Fenom::AUTO_STRIP);
```

**Comment by maxicms** [comment]
Значит мне как и в прошлый раз повезло споймать странный баг, который не повторяется у других.  :)

**Comment by Sleuthhound** [comment]
Вы через маску задаешь или массив?

**Comment by maxicms** [comment]
$fenom = Fenom::factory(
                $tpl_folder,
                PATH . '/cache',
                array(
                    'auto_reload'   => true,
                    'force_include' => true
                )
            );

**Comment by bzick** [comment]
Странно, проверю тесты.  @maxicms может пока скинете образец где не работает?

**Comment by Sleuthhound** [comment]
С утречка попробовал еще раз - работает.
```
$fenom = Fenom::factory(
    '../application/Views/Template',
    '../application/Caches',
    array(
       'auto_reload' => true,
       'force_include' => true,
       'strip' => true
    )
);
```

**Comment by Sleuthhound** [comment]
При включенной опции FENOM::AUTO_STRIP и использовании коротких комментариев во вставках JavaScript - кеш шаблона в этих местах представляет из себя одну строку с нарушенной структурой JS. Используем в этом случает многострочные комментарии.
Может добавить при включенном AUTO_STRIP вырезание всех комментариев из кода?

**Comment by bzick** [comment]
Это довольно затруднительно так как AUTO_STRIP не вкурсе какой код (js, html или даже комбинированный вариант) он обрабатывает.

**Comment by diz-dozer** [comment]
Странная работа . при     'strip' => true'  .. обрезает не все пробелы в шаблоне .. остаются  множественные whitespace

`<!doctype html> <html class="no-js" lang="ru">  <body id="login">     </body> </html>`

а хотелось бы так:
`<!doctype html><html class="no-js" lang="ru"><body id="login"></body></html>`

**Comment by pafnuty** [comment]
@Sleuthhound возможно стоит попробовать вынести js в отдельный файл?
Илил есть непреодолимые сложности?

**Comment by Sleuthhound** [comment]
Бывает, что код надо собрать из заранее динамически сформированных кусочков, а я привык одно строчные комментарии лепить, сначала не понял, что за глюк, а потом дошло))

**Comment by pafnuty** [comment]
Да, однострочные небольшие комментарии удобнее и писать и читать.
Но я всегда стараюсь выносить js в js-файлы, а если есть динамические данные, то стараюсь рассовывать по data-* атрибутам тегов (как правило динамика заключается в данных для обработки событий) и уже их отлавливаю в js. 
Если данных много пишу примерно так:
```
<button data-params='{"param1": "data1", "param2": "data2"}'>купить</button>
```
В данном случаи очень удобно пользоваться `json_encode()`? да и с данными проще работать потом :smile:

**Comment by Sleuthhound** [comment]
Так то да, надо будет пересмотреть все, сейчас пока просто делаю, лишь бы работало)) Набросок функционала, так сказать.

**Comment by bzick** [comment]
Проверьте, должна работать в последних версиях шабонизатора
