### ISSUE TITLE
Отправка кода состояния и заголовков HTTP

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#143]
А можете добавить функционал для отправки кода состояния и заголовков HTTP? Было бы удобно все через одну библиотеку формировать.

**Comment by pafnuty** [comment]
Так ведь можно это сделать самостоятельно, просто добавив собственный тег к примеру.

**Comment by Sleuthhound** [comment]
Можно, но хотелось бы, чтобы при вызове $fenom->display() заголовки отправлялись, а при $fenom->fetch(), соответственно, нет. Может подскажете, как реализовать это, через свои теги?

**Comment by bzick** [comment]
Как-то так
```php
$fenom->addFunction('headers', function ($params) {
	if(isset($params['code'])) {
		header($params['header'], true, $params['code']);
	} else {
		header($params['header']);
	}
});
```
использование:

```smarty
{headers header="Content-Type: text/html; charset=UTF-8"}
{headers header="Ok" code=200}
```

**Comment by Sleuthhound** [comment]
Спасибо!

**Comment by bzick** [comment]
Отследить что?

**Comment by Sleuthhound** [comment]
В моем случае, оказалось, что вашего примера более чем достаточно. Я имел ввиду, как происходит вывод контента $fenom->display() или $code = $fenom->fetch().
Еще раз спасибо)

**Comment by bzick** [comment]
Только сейчас догнал что требовалось. Определить что сейчас display или fetch очень просто. fetch использует ob_start(), следовательно если ob_get_level() > 0 то fetch, иначе display. Конечно есть свои тонкости, например если у вас нет ob_start() вне Fenom.

**Comment by Sleuthhound** [comment]
Странно, но в моем случае ob_get_level() всегда больше 0.
ob_get_level() = 1 при использовании display(), ob_get_level() = 2 при fetch().

**Comment by bzick** [comment]
Все-таки я рекомендую  заголовки слать до отрисовки шаблонов, это не то чем должен заниматься шаблонизатор. Но если так надо, то добавить функцию или модификатор, которая будет проверять вывод и отправлять заголовки - единственное решение.
