### ISSUE TITLE
Про логические выражения... это фича или бага?)

### ISSUE THREAD

**Issue by alexandr-v** [fenom-template/fenom#144]
Сразу примеры:

```html
{true} - выводит 1/true (ок)
{!true} - выводит пустую строку (ок)

{var $b = true}
{$b} - выводит 1/true (ок)
{!$b} - выводит пустую строку (ок)

<!-- $o->myFunc() === true -->
{$o->myFunc()} - выводит 1/true (ок)
{!$o->myFunc()} - выводит 1/true (как так? должно быть пустая строка/false)
{!($o->myFunc())} - выводит пустую строку/false (ок)
```
и это актуально в блоке if...

а вот еще
```html
{var $b = 5}
{$b == 5 ? '5' : '?'} - выводит 1/true (как так? должно быть 5)
{($b == 5) ? '5' : '?'} - выводит 5 (ок)
```
Я вот не пойму, скобки обязательны получается?

**Comment by bzick** [comment]
с `{!$o->myFunc()}` глупо вышло. После рефакторинга по обработке цепочек `$a->b->c->d...` забыл прикрепить унарные операторы. Багу исправил.
А вот тернарный оператор не в той последовательности применялся,  то есть получалось что `{$b == 5 ? '5' : '?'}` это `{$b == (5 ? '5' : '?')}`. Исправил.
На оба бага добавил тесты что бы не прозевать.

**Comment by alexandr-v** [comment]
Спасибо!)
