### ISSUE TITLE
Планируется ли интеграция с Laravel?

### ISSUE THREAD

**Issue by pafnuty** [fenom-template/fenom#146]
[Laravel](http://laravel.com/) довольно популярный фреймворк, но его шаблонизатор довольно своеобразен.
Не планируется ли интегрция?

**Comment by maxicms** [comment]
так можно самому написать аддон и выложить в тут :)

**Comment by pafnuty** [comment]
@maxicms так я поэтому и спрашиваю. Начну писать, а кто-то уже сделал :smile: 
Думаю моих очень скромных знаний php + пример интеграции Smarty должно хватить на базовую интеграцию фенома.

**Comment by bzick** [comment]
Как закончу [smarty-fallback](https://github.com/fenom-template/smarty-fallback) гляну что там, опыт с Laravel был, маленький, но был

**Comment by pafnuty** [comment]
@bzick Классно!
Я нашел два репа с интеграциями Smarty:
- https://github.com/lukeforeman/Laravel4-SmartyView 
- https://github.com/Latrell/Smarty

**Comment by maxicms** [comment]
суть в том чтобы начать, а тут смотри и я подтянусь еще и автор fenom, в этом плюс коллективной разработки :) Про скомные знания php - немного повеселило, просто я очень много людей знаю заочно и только по никам, Ваш знаю давно и если честно то даже начинал php учить по некоторым ваши скриптам. :)

**Comment by pafnuty** [comment]
@maxicms я вообще php не учил, ни одной книжки не прочитал по php, ни одного курса, вообще ничего. Только гугл, php.net и т.п. Так что знания мои действительно очень скромны.

**Comment by aios** [comment]
@pafnuty не скромничай)

**Comment by maxicms** [comment]
Уже сделали :)

**Comment by pafnuty** [comment]
@maxicms только ты [ссылку на репозиторий с интеграцией](https://github.com/fenom-template/Laravel.Fenom) забыл добавить.
