### ISSUE TITLE
Расширение глобальной переменной

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#149]
Подскажите, так и должно быть?
```php
$fenom->addAccessor('array', function (Fenom\Tokenizer $tokens) { 
    return array('key' => 'val');
}); 
```
```php
{$.array.key}
```
На выходе получаем:
```html
 Unexpected token '.' ... либо Unexpected token '->' ... если имеем дело с объектом
```

**Comment by Sleuthhound** [comment]
Дошло, тут получается надо самостоятельно разбирать токены.

**Comment by bzick** [comment]
Да, глобальная переменная обрабатывается во время компиляции. То есть accessor коллбек возвращает PHP код (строка), который будет выполнен во время отрисовки шаблона. Если вам надо вызвать некую функцию то можно написать следующее:
```php
$fenom->addAccessor('array', function (Fenom\Tokenizer $tokens) { 
	return 'my_accessor_array("'.$tokens->next()->getAndNext().'")';
}); 

// $.array.key вызовет my_accessor_array("key")
```
Подробней о том что в коде выше произошло:

 `$.array.key` это токены `$`, `.`, `array`, `.`, `key`. Причем токены `$`, `.`, `array` разбираются системой, а далее предлагается самим разобрать токены `.`, `key`. Так как Вы не использовали оставшиеся токены то Fenom выбросил ошибку после разбора тега, так как не разобранных токенов не должно быть, все должно быть при деле.
Так как нас токен `.` не интересует то мы его пропускаем методом `->next()` и берем следующий токен  `key` сдвигая указатель в массиве токенов на следующий элемент методом `->getAndNext()`, показывая что мы обработали свои токены, остальное нас не интересует.

**Comment by bzick** [comment]
В случае массива будет
```php
$fenom->addAccessor('array', function (Fenom\Tokenizer $tokens) { 
    return '$array["'.$tokens->next()->getAndNext().'"]';
}); 
```

**Comment by bzick** [comment]
Надеюсь объяснение помогло

**Comment by Sleuthhound** [comment]
Да, пока просто выстраиваю цепочку вызовов методов и свойств без проверок:
```php
$fenom->addAccessor('object', function (Fenom\Tokenizer $tokens) {
    while ($tokens->valid()) {
        if ($tokens->is('.')) {
            $callable[] = "['". $tokens->skip('.')->getAndNext() ."']";
        } else {
            $callable[] = $tokens->getAndNext();
        }
    }
    return 'Class::$object'. join('', $callable);
});

**Comment by bzick** [comment]
то что foreach не воспринимает — баг, буду править

**Comment by bzick** [comment]
В 2.5 теперь foreach воспринимает глобальную переменную

**Comment by Sleuthhound** [comment]
Спасибо!

**Comment by Sleuthhound** [comment]
Подскажите, как правильно сформировать вывод в функции, обрабатывающей пользовательский акцессор, когда происходит их сравнение. Например:
```php
{if $.myAccesor ?}
   ...
{/if}
```

**Comment by bzick** [comment]
Рекомендую глянуть сюда — https://github.com/fenom-template/fenom/blob/master/src/Fenom/Accessor.php#L41
Это обработка глобальных типа `$.get`, `$.post` и тд

Токен `?` будет переменной сам в глобальной переменной. Но глобальная переменная не воспринимается парсером как переменная, а как некий набор действий, поэтому он не может применить к ним `empty` и по этой причине нельзя задавать значение глобальной переменной то есть `$.get.one = 1` работать не будет.

**Comment by Sleuthhound** [comment]
Пока изменил предыдущий вариант https://github.com/fenom-template/fenom/issues/149#issuecomment-75248814 на такой:
```php
$fenom->addAccessor('object', function ($tokens, $tpl) {
    $body = 'Class::$object';
    while ($tokens->valid()) {
        if ($tokens->is('.')) {
            $body = $tpl->parseVariable($tokens, $body);
        } elseif ($tokens->is('|')) {
            $body = $tpl->parseModifier($tokens, $body);
        } elseif ($tokens->is('?') || $tokens->is('!')) {
            $body = $tpl->parseTernary($tokens, $body, true);
        } elseif ($tokens->is('->')) {
            $body = $tpl->parseChain($tokens, $body);
        } else {
            $body .= $tokens->getAndNext();
        }
    }
    return $body;
});
```
С первого взгляда вроде получилось, то что нужно. Можно применять модификаторы и использовать в условных операторах.

**Comment by bzick** [comment]
ну Вы немного перестарались) Но Ваш вариант работоспособен. Однако Вам достаточно

```php
$fenom->addAccessor('object', function ($tokens, $tpl) {
    return 'Class::$object';
});
```

Остальное распарсит сам шаблонизатор (точку, модификаторы, условные операторы и тд), то есть будут работать:

```smarty
$.object->a
$.object->a->b->c
$.object.a
$.object.a->b ?: $c
```
и прочие операции над значением, которые существуют в Fenom

**Comment by bzick** [comment]
Ах, стоп. Я Вас ввел в заблуждение, данная возможность еще в разработке, когда шаблонизатору можно сказать самому допарсить по правилам.

**Comment by Sleuthhound** [comment]
Хм, у меня ошибку выдает

**Comment by bzick** [comment]
Да, я написал о своей оплошности выше. Вариант, который я описал будет доступен в следующей версии

**Comment by bzick** [comment]
будущий вариант будет иметь 3ий аргумент  в методе addAccessor, который укажет парсеру что надо распаристь самостоятельно и как

**Comment by bzick** [comment]
Однако, отчасти я прав в том что когда вами будет обработана глобальная переменная, то парсер сам спарсит модификаторы и условные операторы. То есть  parseModifier и parseTernary лишние

**Comment by Sleuthhound** [comment]
Ага, вы правы. Переделал так:
```php
$fenom->addAccessor('object', function ($tokens, $tpl) {
    $body = 'Class::$object';
    $body = $tpl->parseChain($tokens, $body);
    $body = $tpl->parseVariable($tokens, $body);
    return $body;
});
```
вроде работает. Спасибо.
