### ISSUE TITLE
Недокументированные модификаторы

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#151]
Случайно заметил, что работают модификаторы при работе с массивами:
{$array|key} {$array|reset} {$array|current} {$array|end} {$array|prev} {$array|next} и, скорее всего, еще какие-то. Очень кстати оказалось.

**Comment by bzick** [comment]
Да, так задуманно. Это указано в документации https://github.com/fenom-template/fenom/blob/master/docs/ru/syntax.md#%D0%9C%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B:

> Кроме того, по умолчанию все функции PHP могут быть использованы в качестве модификаторов (что можно отключить в настройках)...

В этом случае нужно знать что к чему применяете так как тут Fenom не проверят типы переменных (передает как есть).
