### ISSUE TITLE
Exception при eval

### ISSUE THREAD

**Issue by Ivan-Baranov** [fenom-template/fenom#152]
Возможно ли при формировании исключения получить информацию о файле шаблона и номере строки?

Fenom/Template.php(454) : eval()'d code on line 88
PHP Parse error:  syntax error, unexpected '(' in

**Comment by bzick** [comment]
Через eval он пытается валидировать шаблон, но у этого способа есть минус — что бы получить код шаблона надо выполнить:
```php
$fenom->compile($template)->getTemplateCode()
```
где `$template` имя шаблона, который падает.
Скиньте строку, на которой происходит ошибка, а так же комментарий выше этой строки (описание тега).

**Comment by bzick** [comment]
Я поправлю, что бы он писал в исключении файл скомпиленого шаблона

**Comment by Ivan-Baranov** [comment]
Скорее всего это из-за включенного отображения Notice
Notice: Trying to get property of non-object

И подключено:
use Symfony\Component\Debug\ErrorHandler;
ErrorHandler::register();

**Comment by bzick** [comment]
Явно не из-за отображения ошибок. Тут явная поломка шаблона последовательностью, которая не тестировалась. Если скинете код или шаблон или хотя бы строку где произошла ошибка мне это упростит поиск проблемы (можно на почту, если конфедициально).

**Comment by Ivan-Baranov** [comment]
Код шаблона:
```
<h1>Test</h1>
{* переменная $a не определена *}
<pre>{$a}</pre>
```

Ошибка во время компиляции шаблона:
Notice: Undefined index: a in .../vendor/fenom/Fenom/Template.php(454) : eval()'d code on line 5

Ошибка после компиляции шаблона:
Notice: Undefined index: a in .../tmp/fenom/test.tpl.127cb255.c.php on line 7

Скомпилированный код:
```php
<?php 
/** Fenom template 'test.tpl' compiled at 2015-02-19 11:49:16 */
return new Fenom\Render($fenom, function ($var, $tpl) {
?><h1>Test</h1>
<pre><?php
/* test.tpl:2: {$a} */
 echo $var["a"]; ?></pre><?php
}, array(
	'options' => 192,
	'provider' => false,
	'name' => 'test.tpl',
	'base_name' => 'test.tpl',
	'time' => 1424346326,
	'depends' => array (
  0 => 
  array (
    'test.tpl' => 1424346326,
  ),
),
	'macros' => array(),

        ));
```

**Comment by bzick** [comment]
Что бы не было `Undefined index` достаточно сказать Fenom-у что бы он проверял переменную перед использованием настройкой `'force_verify' => true`:

```php
$fenom->setOptions(array(
    "force_verify" => true
));
```

Меня интересует та фатальная ошибка, которая упомянута в первом сообщении. Ее удается повторить?

**Comment by Ivan-Baranov** [comment]
```php
/* test.tpl:1: {$i->slug == $cur ? 'class="current"' : ''} */
 echo (empty(($var["i"]->slug == $var["cur"])) ? '' : 'class="current"'); ?>>qqq</li><?php
```

**Comment by bzick** [comment]
Исправил (2.5.4)
