### ISSUE TITLE
Динамический вызов макроса.

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#156]
Я правильно понимаю, динамически вызвать макрос не возможно? Блоки получается тоже нельзя задавать динамически. В дальнейшем не планируется ли добавление такой возможности?
```php
{macro.$name x=$num y=100}
```

**Comment by bzick** [comment]
Динамические блоки усложняли алгоритм наследования шаблона и делали его очень медленным, от них пришлось отказаться. Они больше не вернутся.
Динамические макросы не задумывался делать. Перед тем как изучать вопрос возможной реализации это фичи я всегда интересуюсь "Зачем? И какую цель тут преследуете?". тут не исключение)

**Comment by Sleuthhound** [comment]
Я пока просто думаю как лучше сделать. В моем случае, после разбора HTTP запроса, определяется раздел запрошенного сайта, компонент (инфобокс) и определенное действие компонента, ну и прочие request данные. Каждый раздел имеет заданный макет дизайна, который может иметь родителя. Реализуется через {extends ...} со статически прописанным именем родителя. При изменении макета {extends} скрыт от пользователя и при сохранении автоматически подставляется, если это дочерний макет.
    Над реализацией инфобокса сейчас работаю. Инфобокс может использовать любую таблицу базы данных и после разбора запроса, создает экземпляр модели (activerecord) заданной таблицы. Далее уже запрошенное действие должно определить, что делать с этим объектом: вывести определенный список записей, добавить, изменить или удалить запрошенную запись и тому подобное, на сколько хватить фантазии.
    Думал, если шаблон инфобокса оформить в виде одного файла, то действия можно прописать в виде макросов и далее исходя из запроса вызывать необходимые. Плюс в том, что в этом случае можно передать в запросе вызов сразу нескольких действий.
    Например вывод списка записей
```php
{macro list($model, $params = null)}
    {set $limit = $params.limit ?: 20}
    {foreach $model->limit($limit)->findMany() as $item}
        {$item->title}...
    {/foreach}
{/macro}
{* импорт макросов в шаблон *}
{import 'infobox.tpl' as action}
{* динамический вызов *}
{foreach $actions as $action}
    {action.action model=$model params=['limit' => 10]}
{/foreach}
```
Потом еще два варианта всплыли на скорую руку, когда прочитал, что динамически макросы вызвать нельзя.
    1. Если отказаться от множественного вызова действий, то можно использовать стандартные блоки условий (if) или переключатели (switch).
    2. Для каждого действия определить свой шаблон, и до него построить цепочку наследования.

**Comment by bzick** [comment]
> При изменении макета {extends} скрыт от пользователя и при сохранении автоматически подставляется, если это дочерний макет.

тут вам стоит использовать динамическое наследование через PHP API:

```php
$fenom->display(["page.tpl", "layout.tpl"], $vars);
```
в  привере page.tpl расширяет layout.tpl, который является макетом (темой). 

Если у вас много разной логики в одном шаблоне, то возможно стоит ее разделить по шаблонам и дальше динамически подключать тот который больше всего подходит под ситуацию:

```php
{include "action/{$action}.tpl"}
```
