### ISSUE TITLE
Кеш и динамическое задание родительского шаблона

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#159]
Каждый раз пересобирается кеш шаблона при использовании динамического имени(значение одно и тоже) в теге {extends}. Так и должно быть?

**Comment by bzick** [comment]
Да, так как это один и тот же шаблон (по имени). Если вы хотите скрыть {extends} и сами им управлять тогда вам лучше и использовать наследование при вызове display/fetch/pipe:

```smarty
$fenom->display(["template.tpl", "layout.tpl"]);
```
в данном случае `layout.tpl` будет унаследован шаблоном `template.tpl`. Количество элементов в массиве может быть любым, последний — конечный макет от которого начинается наследование.

**Comment by Sleuthhound** [comment]
Супер, можно было все гораздо проще реализовать. В документации вроде везде встречал, что значение у метода display(string $template, ...). Даже и не думал, что так можно :) .Теперь при сохранении макетов не нужно вычислять значение для тега {extends}. Спасибо за пояснение, а может еще есть какой нить недокументированный, интересный и удобный функционал?

**Comment by bzick** [comment]
Да, с документацией не ахти сейчас. Мне всегда тяжело ее писать. Всяких фич полно, например игнорирование в любом теге:

```smarty
{if:ignore $scripts}
<script>
var a = {c:4};
</script>
{/if}
```
все что в if будет проигнорировано компилятором

**Comment by bzick** [comment]
Полагаю, вопрос решен

**Comment by pafnuty** [comment]
@bzick вот так вот и узнаю о новых возможностях шаблонизатора. 
Спасибо. Как раз недавно требовалась конструкция с `{if:ignore ...}`

**Comment by kirilltitov** [comment]
Не очень приятно, что при передаче в fetch или display шаблонов как массива игнорируется директива extends внутри шаблонов. Да, это возможность выстрелить себе в ногу (например, если встретятся противоречивые extends, да и вообще больше одного тэга extends), но мне кажется, это всё-таки стоит разрешить.

**Comment by bzick** [comment]
Не игнорируется, если есть extends в шаблоне то он выполнится, а потом дальше пойдет по массиву наследовать шаблоны. Как и с любым другим инструментом с этой возможностью надо обращаться осознано. Хотя ничего неожиданного тут нет.

**Comment by kirilltitov** [comment]
И тем не менее, у меня не получилось. Скажем, есть шаблон layout.tpl, в котором базовая разметка и раскиданы пустые блоки (в расчете на то, что их переопределят). Есть шаблон index.tpl, в котором есть тэг extends и определено несколько блоков. Если я вызываю $fenom->display('index.tpl'), то все ок, наследование отрабатывает как надо. Если же я вызываю $fenom->display([ 'index.tpl' ]), то на экране ничего, т.е. тэг extends игнорируется.

**Comment by bzick** [comment]
Это легко объяснить. когда вызываете $fenom->display([ 'index.tpl' ]) феном собирает блоки из index.tpl что бы передать следующему шаблону, которого нет. поэтому он ничего не нарисовал. Не знаю, бага или фича это. Вместо $fenom->display([ 'index.tpl' ]) используйте $fenom->display('index.tpl')

**Comment by bzick** [comment]
То есть должно быть как минимум 2 элемента в массиве

**Comment by kirilltitov** [comment]
>феном собирает блоки из index.tpl что бы передать следующему шаблону
вроде как это и означает, что в таком случае он игнорирует тэг extends?

Ладно, два шаблона. Я вызываю $fenom->display([ 'debug.tpl', 'index.tpl' ]) где в debug.tpl есть только переопределение блока dbg (оригинально определенного в layout.tpl), а index.tpl внутри наследует layout.tpl. Происходит ничего.

Я рассчитываю на поведение (уж простите) из Смарти, где можно было сделать такой же финт через $smarty->display('extends:index.tpl|debug.tpl') и всё работало бы из коробки.

Иными словами, я доверяю своим шаблонам. Они могут наследовать что угодно. Но в то же время иногда у меня есть необходимость добавить в определенные места очереди дополнительные шаблоны, которые будут переопределять отдельные блоки. Или, если им сильно захочется, сами наследоваться от чего-то.

Возвращаюсь к своей реплике — это шикарный способ выстрелить себе в колено, что я часто и практиковал, сидя на Смарти. И мне не хватает этого же вполне логичного (хоть и опасного) функционала в Феноме.

Резюмируя. Я не вижу идеологических причин, по которым $fenom->display([ 'index.tpl' ]) должно отрабатывать иначе, чем $fenom->display('index.tpl').

**Comment by bzick** [comment]
Согласен с вами. Исправлю в следующем релизе

**Comment by kirilltitov** [comment]
Не забудьте, пожалуйста, про эту проблему :)

**Comment by bzick** [comment]
@kirilltitov исправлено
