### ISSUE TITLE
strip=>true  оставляет множественные пробелы

### ISSUE THREAD

**Issue by diz-dozer** [fenom-template/fenom#162]
Странная работа . при 'strip' => true' .. обрезает не все пробелы в шаблоне .. остаются множественные whitespace

 `<!doctype html> <html class="no-js" lang="ru"> <body id="login"> </body> </html>`

а хотелось бы так:
`<!doctype html><html class="no-js" lang="ru"><body id="login"></body></html>`

**Comment by pafnuty** [comment]
Множественные пробелы логично преврашать минимум в единичные пробелы т.к. нет гарантии, что это разрыв слов к примеру.
Проблема решается на уровне фильтров.
```smarty
{filter|strip|replace:["\n","\t"]:""|replace:"> <":"><"|strip}
<!doctype html>
<html class="no-js" lang="ru">
	<body id="login">
		...
	</body>
</html>
{/filter}
```

**Comment by diz-dozer** [comment]
Может поправить  RegExp (strip)?
Использование фильтра похоже на костыль.. ИМХО

**Comment by pafnuty** [comment]
Насколько я понял только `filter` можно применить к фрагменту шаблона, а уж что ему скармливать это вам решать, я навскидку набросал код :smile:

**Comment by bzick** [comment]
Исправлено в  2.8.1
