### ISSUE TITLE
Использование блоков в шаблонах

### ISSUE THREAD

**Issue by cpnemo19** [fenom-template/fenom#163]
Я, кажется, запутался в использовании блоков, или не совсем понимаю их реализацию. Для примера, имеется файл с "библиотекой" часто используемых блоков 'blocks.tpl'

{ block 'search'}
   < form class="search" method="post" action="/search.php">
     <_input name="search" value="" type="text" />
     <_input name="submit" value="Go" type="submit" />
   < /form>
{ /block}
{ block 'login'}
   < form class="login" method="post" action="/login.php">
      Логин: <_input name="name" type="text" />
      Пароль: <_input name="pswd" type="password" />
     <_input name="submit" value="Login" type="submit" />
   < /form>
{ /block}

Как, каким образом, вызвать блоки,описанные в файле blocks.tpl, в разных шаблонах?
Если предполагалось {extends 'parent.tpl'}, то для "библиотечного" блока нет возможности указать родительский шаблон. Он не известен заранее, блоки могут использоваться во многих шаблонах, собираемых из таких мелких блоков.
Если {use 'blocks.tpl'} - от эти мелкие блоки хотелось бы размещать не в одном месте, друг за другом, а в конкретных местах страницы. 
Если в одном файле - один блок, то даже для некрупного проекта их получается достаточно много, что не удобно.

Что посоветуете?
PS: То есть хотелось бы иметь интерфейс вызова нужного блока в нужном месте...

**Comment by bzick** [comment]
> Если {use 'blocks.tpl'} - от эти мелкие блоки хотелось бы размещать не в одном месте, друг за другом, а в конкретных местах страницы. 

не понимаю предложение, можете привести пример?

> PS: То есть хотелось бы иметь интерфейс вызова нужного блока в нужном месте...

ну понимаете, что бы вызвать блок надо знать  где он находится. Для этого введен тег  {use ...}, который явно указывает на набор блоков. Я не понял чем он вам не подходит. Не хватает примеров.

**Comment by bzick** [comment]
о, кажется понял

**Comment by bzick** [comment]
На самом деле вам бы  нужны [макросы](https://github.com/fenom-template/fenom/blob/master/docs/ru/tags/macro.md), фрагменты шаблонов, которые можно вставить куда хотите.
**forms.tpl**:
```smarty
{macro search}
<form class="search" method="post" action="/search.php">
<input name="search" value="" type="text" />
<input name="submit" value="Go" type="submit" />
</form>
{/macro}

{macro login}
<form class="login" method="post" action="/login.php">
Логин: <input name="name" type="text" />
Пароль: <input name="pswd" type="password" />
<input name="submit" value="Login" type="submit" />
< /form>
{/macro}
```

**любой-шаблон.tpl**:
```smarty
...
{import 'forms.tpl' as forms}
 {* подключили бибилиотеку с макросами, 
 указав им пространство имен forms (по умолчанию macro) *}
...
{forms.login} {* вызовет макрос login и нарисует форму авторизации *}
...
{forms.search} {* вызовет макрос search и нарисует форму поиска *}
...
```

макросы, как и блоки, заточены для быстрой работы. по возможности, они стараются вшить свой код прямо в итоговый шаблон, что бы не тратить ресурсы на поиск макроса в системе и вызовы методов.

**Comment by cpnemo19** [comment]
Да, спасибо. 
Вариант через макросы я рассматривал, но подумал что это идеологически некорректно. 

>макросы, как и блоки, заточены для быстрой работы. по возможности, они стараются 
>вшить свой код прямо в итоговый шаблон, что бы не тратить ресурсы на поиск 
>макроса в системе и вызовы методов.

В таком случае встает вопрос - чем, каким уникальным свойством, обладают блоки, что не может быть реализовано на макросах? 
;)

**Comment by bzick** [comment]
У них разные цели. Блоки - разметка шаблона. блоками вы указываете задуманные вами места в шаблоне. Например, шаблон с дизайном имеет блоки content (контентная часть), footer(место под контентом, под счетчики например), header (место над контентом, для меню например) и тд. Другим же не нужно парится над дизайном и достаточно указать что они хотят вывести в content, footer, header и унаследовать шаблон с дизайном. И не обязательно описывать все блоки.
