### ISSUE TITLE
глобальность переменных цикла

### ISSUE THREAD

**Issue by litvinenkow** [fenom-template/fenom#166]
интересный баг поймал
сразу оговорюсь, во все шаблоны летят все глобальные переменные

есть один шаблон, в нем цикл foreach
{foreach $top as $kk=>$cat}
...
{/foreach}
он компилится через fetch

при этом в глобальных переменных уже есть $cat и она определена согласно скрипта и не переопределяется

есть еще более верхний шаблон, он компилится через display, и вот в нём переменная $cat уже получается инициализированной как последний элемент цикла, хотя теоретически должна туда попасть та которая в глобальной области видимости была
долго не мог понять в чём дело ибо неочевидный баг

может я что-то делаю не так, но мне кажется это немного неправильное поведение

**Comment by Sleuthhound** [comment]
Как полагаю, вы реализуете полет глобальных переменных в шаблоны по аналогии: 
```php
$fenom = Fenom::factory(__DIR__, __DIR__, array());
$template1 = $fenom->fetch('template1.tpl', $GLOBALS);
$fenom->display('template2.tpl', $GLOBALS);
```
либо
```php
$array = $GLOBALS;
$fenom = Fenom::factory(__DIR__, __DIR__, array());
$template1 = $fenom->fetch('template1.tpl', $array);
$fenom->display('template2.tpl', $array);
```
...
$GLOBALS состоит из ссылок на все переменные глобальной области видимости, и если вам, все же, необходимо передавать все переменные в шаблонизатор, хотя мне кажется это очень избыточным, можно реализовать как-то так:
```php
foreach ($GLOBALS as $key => $val) { $array[$key] = $val; }
$fenom = Fenom::factory(__DIR__, __DIR__, array('auto_reload' => true,'force_include' => true));
$template1 = $fenom->fetch('template1.tpl', $array);
$fenom->display('template2.tpl', $array);
```

**Comment by bzick** [comment]
как вы создаете и вызываете fenom?

**Comment by bzick** [comment]
Полагаю вопрос решен?
