### ISSUE TITLE
Опция Fenom::DISABLE_CACHE

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#171]
Подскажите, так и должно быть?
1. По умолчанию кеширование включено.
2. Создаем шаблон с начальным содержимым, выводим. В кеше появляется компилированный файл.
3. Выключаем кеширование, чуток изменяем содержимое файла, еще раз просматриваем.
4. В кеше появляется второй компилированный файл.
5. Еще раз изменяем содержимое шаблона. На выходе отображается содержимое из пункта 3.
6. Включаем кеширование и еще раз просматриваем. На выходе содержимое из пункта 2.

Третий вариант шаблона отображается только после очистки кеша, либо при включенной опции Fenom::AUTO_RELOAD

Версия 2.7, отображение формируется согласно https://github.com/fenom-template/fenom/issues/159#issuecomment-75962673

**Comment by Sleuthhound** [comment]
Не знаю на сколько корректно, для себя, временно, решил вопрос так:
вставил вместо строки https://github.com/fenom-template/fenom/blob/master/src/Fenom.php#L961
```php
        } elseif ($this->_options & self::DISABLE_CACHE) {
            return $this->compile($template, false, $options);
        } else {
```

**Comment by bzick** [comment]
Исправлено в 2.8.0

**Comment by Sleuthhound** [comment]
Все равно не понимаю немного алгоритм кеширования. При выключенном кешировании теперь все работает как нужно. Но если мы поочередно меняем опции кеширования, то создаются несколько разных файлов, которые потом также поочередно выводятся при обратном отключении, что вводит в заблуждение.

Просто включенное кеширование:
![2015-09-21 21 52 24](https://cloud.githubusercontent.com/assets/1821565/9998686/e12fd7e2-60ab-11e5-97a1-6d66759adfa9.png)
![2015-09-21 21 52 46](https://cloud.githubusercontent.com/assets/1821565/9998693/eb016100-60ab-11e5-9840-5697e1977f6a.png)

Если макет изменился:
![2015-09-21 21 53 30](https://cloud.githubusercontent.com/assets/1821565/9998767/3d0fcbd0-60ac-11e5-8407-ed80fead75c4.png)
![2015-09-21 21 53 48](https://cloud.githubusercontent.com/assets/1821565/9998770/3f7ad928-60ac-11e5-9576-fcc11b4c2e1f.png)

Если каждый раз собирать по новой:
![2015-09-21 22 00 24](https://cloud.githubusercontent.com/assets/1821565/9998787/5aeba8ae-60ac-11e5-85bc-b0988dd9c58d.png)
![2015-09-21 21 59 44](https://cloud.githubusercontent.com/assets/1821565/9998794/619e0c32-60ac-11e5-97c3-25d57f9b0c9f.png)

В итоге, когда меняем на простое кеширование, видим начальный вариант макета. Хотя, после всех манипуляций, интуитивно ожидаешь вывод конечного результата.

Так и должно быть? Или просто, при проектировании не учитывался тот вариант, что настройки шаблонизатора могут постоянно меняться?
