### ISSUE TITLE
Проблема с расширением глобальной переменной

### ISSUE THREAD

**Issue by BTPAHCE** [fenom-template/fenom#174]
После создания объекта fenom добавляю новую переменную:
$fenom->addAccessor('site_name', function (Fenom\Tokenizer $tokens) { return 'Адрес сайта'; });
Все хорошо, но вывод из шаблона {$.site_name} выдает ошибку:

Fatal error: Cannot use object of type Closure as array in /classes/Fenom/Template.php on line 994

**Comment by BTPAHCE** [comment]
Кто-нибудь поможет решить проблему?

**Comment by maxicms** [comment]
Уже :)

**Comment by bzick** [comment]
Исправлено в 2.7.1
Замечу что должно быть
`function (Fenom\Tokenizer $tokens) { return 'echo "Адрес сайта";'; }`

так как акцессор должен возвращать PHP код

**Comment by BTPAHCE** [comment]
Parse error: syntax error, unexpected T_ECHO in /var/www/nazaroff/data/www/7774545.ru/classes/Fenom/Template.php(462) : eval()'d code on line 6 Warning: Cannot modify header information - headers already sent by (output started at /var/www/nazaroff/data/www/7774545.ru/classes/Fenom/Template.php(462) : eval()'d code:111) in
