### ISSUE TITLE
Проблема вложенных шаблонов.

### ISSUE THREAD

**Issue by maxicms** [fenom-template/fenom#176]
При использовании авто загрузчика плагинов и использовании include или insert другого шаблона происходит баг при повтором обновлении страницы будет ошибка об отсутствии функции из вложенных шаблонов.

**Comment by bzick** [comment]
для загрузки плагинов используете https://github.com/fenom-template/fs-entity-loader ?

**Comment by maxicms** [comment]
да именно его.
