### ISSUE TITLE
Опять вопрос про json в шаблонах.

### ISSUE THREAD

**Issue by maxicms** [fenom-template/fenom#177]
В последнее время перешел больше на использование динамических данных, и встала проблема с использованием fenom в частности 
вот такой код 
```
<div class="page-bar" data-settings="{'page':{$page},'total':{$total},'maxVisible':5}">
```
очень хотелось бы иметь возможность чтобы fenom понимал что это json строка и не пытался первые скобки использовать как начало тега для парсинга. 

Многие сейчас скажут что можно просто поставить пробел, но оператора .data не разбирает данный текст как json считая его не валидным.

**Comment by bzick** [comment]
по каким критериям предлагаете определять что это  JSON?

**Comment by maxicms** [comment]
вопрос на засыпку, но для того чтобы код был валидным при использовании в html 5 требуется все ключи и значения брать в кавычки одинарные можно конечно проверять на такой код "{' то есть если после открывающего тега стоит одинарная кавычка, его игнорировать

**Comment by bzick** [comment]
За кавычки особо не зацепишься. Замечу что по формату JSON должен иметь только двойные кавычки, в противном случае `JSON.parse(...)` выбросит ошибку `Unexpected token '`.

**Comment by maxicms** [comment]
Согласен на 100% просто сегодня уже 3 часа ставлю эксперименты, если сделать " то .data(''setting") вернет строку в не объект, и наоборот если сделать одинарные кавычки то JSON.parser ругнется.  

Есть предложение сделать что то типа экранирования, можно попробовать сделать вот так 
```
<div class="page-bar" data-settings="{{'page':{$page},'total':{$total},'maxVisible':5}}">
```
И такой вариант уже рассматривать как json. Хотя тоже костыльное решение.

**Comment by maxicms** [comment]
Вопрос можно закрывать так как решил что не стоит все лепить в кучу и лишний раз раздувать и без того крутой функционал шаблонизатора. Для решения свой задачи заставил себя прочитать мануал и просмотреть исходники юнит тестов, чтобы за пару минут решить задачу с которой возился полдня. 

Результатом стала обычная блочная функция
```
<div id="page_bar" class="page_bar" data-settings="{json}"page":{$page},"total":{$pages}{/json}"></div>
```

Меня такое решение устраивает на 1000% даже видно что это json параметры.

**Comment by pafnuty** [comment]
Ну для начала не совсем корректный json в атрибуте, такой масив надо ещё прогонять через `$.parseJSON` 
Попробуй написать так:
```smarty
{set $json ['page' => $page, 'totel': $total ]}
<div id="page_bar" class="page_bar" data-settings='{$json|json_encode}'></div>
```
Атрибут именно в однарных кавычках т.к. json_encode вернёт двойные.
Тогда при передаче в js легко получаем объект 
```javascript
console.log($('.page_bar').data('settings'));
```

**Comment by maxicms** [comment]
да можно и так , но мои вариант заработал и пока это главное.

**Comment by pafnuty** [comment]
Ещё вариант — перенос строки посл открывающей фигурной скобки:
```smarty
<div id="page_bar" class="page_bar" data-settings='{
"page":{$page},"total":{$pages}
}'></div>
```

**Comment by maxicms** [comment]
почему не корректный JSON у меня?

**Comment by pafnuty** [comment]
у тебя значение атрибута в двойних кавычках, нужно в одинарных т.к. внутри используешь двойные. + если вдруг будет текст  - есть вероятность некорректной обработки.
пример 
`{"foo": "15 000 руб", "bar": "и ещё какой нибудь спецсимвол вроде & "}`
если это не обработать json_encode будет ошибка.

**Comment by maxicms** [comment]
За кавычки особо не зацепишься. Замечу что по формату JSON должен иметь только двойные кавычки, в противном случае JSON.parse(...) выбросит ошибку Unexpected token '.
С этим я согласен с Иваном.

**Comment by maxicms** [comment]
Согласен, только суть в другом я же лишний раз перестраховался, {json} это блоковая функция, она просто добавляет { } и экранирует кавычки чтобы не вляпаться в кавычки атрибута.
