### ISSUE TITLE
Номер текущего прохода в цикле в глобальной переменной

### ISSUE THREAD

**Issue by BTPAHCE** [fenom-template/fenom#179]
Например как это сделано в smarty там через глобальную переменную можно получиться номер операции прохождения массива через foreach. Очень удобно делать нумерованные списки. Сейчас же приходиться объявлять переменную потом прибавлять единицу каждый цикл.

**Comment by pafnuty** [comment]
Про тег [{foreach}](https://github.com/fenom-template/fenom/blob/master/docs/ru/tags/foreach.md#foreach) читали?
![fenomforeach md at master fenom-templatefenom opera](https://cloud.githubusercontent.com/assets/1635679/9150732/650f9188-3df2-11e5-93d8-1b9117f29f2a.png)

**Comment by BTPAHCE** [comment]
Спасибо
