### ISSUE TITLE
Про вложенные шаблоны

### ISSUE THREAD

**Issue by BTPAHCE** [fenom-template/fenom#180]
Есть шаблон a.tpl, он вызывает шаблон b.tpl (include)
Как в шаблоне b.tpl получить имя шаблона вызвавшего его? То есть имя шаблона: a.tpl

**Comment by pafnuty** [comment]
У меня возникает стойкое ощ ущение, что либо вы совсем не читаете доки, либо они очень плохо написаны.
Попробуйте передавайте название текущего шаблона в include, в глобальных переменных есть имя текущего шаблона, в доках по тегу include есть пример с параметрами.

**Comment by BTPAHCE** [comment]
Все это я знаю. Просто подумал есть решение как смотреть имя шаблона родителя без передачи явно через переменную.

**Comment by pafnuty** [comment]
Думаю, что это наилучший вариант, ведь шаблон может быть и не один раз вложен.
К примеру если реализовать получение родителя без явной передачи его имени в дочерний, то как быть с "внуками и правнуками"? Навернка сильно усложнит работу шаблонизатора, поэтому и не реализовано.
