### ISSUE TITLE
Проблема с глобальной переменной

### ISSUE THREAD

**Issue by BTPAHCE** [fenom-template/fenom#181]
$fenom -> addAccessor('site_name', function (Fenom\Tokenizer $tokens) { return 'echo 'Адрес сайта';'; });

Проблема не решилась((

Parse error: syntax error, unexpected T_ECHO in /classes/Fenom/Template.php(462) : eval()'d code on line 6 Warning: Cannot modify header information - headers already sent by (output started at /classes/Fenom/Template.php(462) : eval()'d code:111) in

**Comment by pafnuty** [comment]
Похоже вы с кавычками перемудрили? попробуйте так:
```
$fenom -> addAccessor('site_name', function (Fenom\Tokenizer $tokens) { return 'echo "Адрес сайта";'; });
```

**Comment by BTPAHCE** [comment]
Ни чего не помогает((((

Parse error: syntax error, unexpected T_ECHO in .../classes/Fenom/Template.php(462) : eval()'d code on line 6 Warning: Cannot modify header information - headers already sent by

**Comment by bzick** [comment]
Скиньте сюда или на мой emial код как добавляете акцессор

**Comment by BTPAHCE** [comment]
$fenom -> addAccessor('site_name', function (Fenom\Tokenizer $tokens) { return 'echo "Адрес сайта";'; });

**Comment by bzick** [comment]
Я понял, это я ввел вас в заблуждение. 
```php
$fenom -> addAccessor('site_name', function (Fenom\Tokenizer $tokens) { return '"Адрес сайта"'; });
```
не надо никаких echo и точек запятой, просто нужно указать код как получить значение. Как его использовать будет решать Fenom исходя из контекста. Прошу прощения, отвечал не подумалв

**Comment by BTPAHCE** [comment]
Ага, спасибо.
Вот только сейчас не пойму как передать туда данные например из внешней переменной.

$fenom -> addAccessor('site_name', function (Fenom\Tokenizer $tokens) { global $config; return '"$config"'; });

Notice: Undefined variable: config in /var/www/nazaroff/data/www/7774545.ru/classes/Fenom/Template.php(462) : eval()'d code on line 6

**Comment by bzick** [comment]
Акцессор должен вернуть  PHP код, который будет выполнен только __во время выполнения шаблона__. Поэтому все не так просто как хотелось бы. Что бы упростить жизнь разработчику есть вариант немного проще:
```php
//  используем шаблонизатор как хранилище наших объектов
$fenom->config = $config;
$fenom->addAccessorSmart('site_name', '$tpl->getStorage()->config', \Fenom::ACCESSOR_VAR });
// $tpl->getStorage() получить объект шаблонизатора в шаблоне, ->config получить наш объект у шаблонизатора
```

**Comment by maxicms** [comment]
А можно узнать более развернутый пример или условие задачи которая требует свои акцессор ? просто мне кажется что все можно решить иначе.

**Comment by bzick** [comment]
Как правило, обычно хватает всем `addAccessorSmart`. Использование `addAccessor` напрямую очень редкое явление так как там надо самим парсить всю цепочку слов: от `$.` и до того момента когда подсчитаете что вам хватит. Наглядные примеры работы с addAccessor можно глянуть в классе  Fenom\Accessor ([список предопределенных акцессоров](https://github.com/fenom-template/fenom/blob/0a8793fe7b22f3047eab44310ab83be40abbf6d0/src/Fenom.php#L67) с парсерам).

**Comment by BTPAHCE** [comment]
Просто хотел передать в $.site_name название сайта
Придется в переменную пихать в шаблон. Ибо я так и не понял как это сделать(

**Comment by maxicms** [comment]
Готовый вариант Вам написали выше.

**Comment by bzick** [comment]
Используйте пример, который описал выше
```php
$fenom->config = [
	"site_name" => // ...
	"site_scripts" => //...
	// и что еще придумете
];
$fenom->addAccessorSmart('site_name', '$tpl->getStorage()->config', \Fenom::ACCESSOR_VAR);
```
Тогда в шаблоне 
```smarty
Site: {$.config.site_name}
```

**Comment by BTPAHCE** [comment]
Спасибо, решил вопрос)
