### ISSUE TITLE
Вопрос про вложенные шаблоны

### ISSUE THREAD

**Issue by BTPAHCE** [fenom-template/fenom#182]
Доброго всем дня)
Подскажите как передать  переменную __*$title*__ из вложенного шаблона __*home.tpl*__?
Что бы эта переменная была доступна в шаблоне __*header.tpl*__

__*header.tpl*__
`<title> {add $title = 'Заголовок по умолчанию'}{$title}</title>`
______________________________________________________
__*index.tpl*__
`{include 'header.tpl'}`
`<div class="container">`
`	{block 'content'}`
`		контент`
`	{/block}`
`</div>`
`{include 'footer.tpl'}`
_____________________________________________________
__*home.tpl*__ - В этом шаблоне мы должны задать переменную __*$title*__
`{extends 'index.tpl'}`
`{block 'content'}content{/block}`

**Comment by pafnuty** [comment]
Если память не изменяет, то **header.tpl:**
```
{block 'title'}Заголовок{/block}
```
**home.tpl:**
```
{block 'title'}Другой заголовок{/block}
```

**Comment by bzick** [comment]
Так  и есть

**Comment by bzick** [comment]
Так как нет комметариев полагаю вопрос решен
