### ISSUE TITLE
Possibility to change provider notation ':'

### ISSUE THREAD

**Issue by pun-ky** [fenom-template/fenom#187]
Hi! I wanna integrate your cool template engine with my application, but I have a problem.

Designers are used to use ':' when they want to reference a template from another app package, but this notation is reserved in Fenom to use another Provider which cause me a few problems.  Maybe there will be a parameter in config or just method Fenom::setScmDelimiter or something like that in future release. It would be great.

Thx in advance.

**Comment by bzick** [comment]
At the moment it is not provided, but this is not difficult. Interesting what kind of delimiter you want to use?

**Comment by pun-ky** [comment]
'::'

**Comment by bzick** [comment]
Still don't see a solid reason to change the delimiter. Templates write you. Why can't you write a colon?

**Comment by bzick** [comment]
No feedback. Close until feedback
