### ISSUE TITLE
Shortcut for unescaped variables

### ISSUE THREAD

**Issue by pun-ky** [fenom-template/fenom#188]
Is there any other way to display raw HTML / unescaped while I have globally turned on 'auto_escape' => true ?

Currently I have tons of usages of helper which is producing <form> tag with CSRF field (Laravel 5 feature):

```
{autoescape false}
    {Form::open(['action' => 'UserController@postLogin'])}
{/autoescape}
```

But I want to do it shorter way e.g:

```
{!Form::open(['action' => 'UserController@postLogin'])!}
```

or use somehow `raw` option but I don't know how.. I didn't see any example for that:

```
{Form::open(['action' => 'UserController@postLogin'])|raw}
```

Please help in a reasonable time.

**Comment by pun-ky** [comment]
I am sorry, yes `raw` is working...
https://github.com/fenom-template/fenom/blob/master/docs/en/tags/raw.md

The problem was in other thing. When I use PHP ... there shouldn't be space before closing '}'

**Comment by bzick** [comment]
Notation {Form::open()} is deprecated, Use system variable `$.` (https://github.com/fenom-template/fenom/blob/master/docs/en/syntax.md#system-variable):

`$.php.form::open()`
