### ISSUE TITLE
Default value if var is empty

### ISSUE THREAD

**Issue by pun-ky** [fenom-template/fenom#189]
Is following feature available somehow?

{$emptyVar or 'default value'}

[return $emptyVar if it contains empty string or null, otherwise return 'default value']

**Comment by bzick** [comment]
Yes, 
`{add $value = 'default value'}` create variable and set string 'default value' if variable $value doesnt exists
or using [ternary operator](https://github.com/fenom-template/fenom/blob/master/docs/en/operators.md#ternary-operators)
`{$emptyVar ?: 'default value'}`

**Comment by pun-ky** [comment]
ok, ternary looks good, thx
