### ISSUE TITLE
Ignoring JSON in data attributes

### ISSUE THREAD

**Issue by pun-ky** [fenom-template/fenom#190]
How about following example:

```
 <a href="{action('PackageController@getUninstall', $package->name())}" rel="tooltip" title="Uninstall" data-confirm='{"message": "Some question?", "cancel": "Cancel", "confirm": "OK"}'>&times;</a>
```

But fenom cries about:

```
Unexpected token ':' in xxx/list.fenom.php line 32, near '{"message":' <- there
```

Whole A tag could be wrapped into {ignore} but I lose possibility to put generated link. Maybe there is some mechanism for escaping '{' and '}' ?

**Comment by pafnuty** [comment]
try this:
```
data-confirm='{
"message": "Some question?", "cancel": "Cancel", "confirm": "OK"
}'
```

**Comment by pun-ky** [comment]
Yes your workaround works... but this also:

data-confirm='{ignore}{"message": "Uwaga! Czy na pewno chcesz odinstalować daną aplikację?", "cancel": "Anuluj", "confirm": "Odinstaluj"}{/ignore}'
