### ISSUE TITLE
Overwriting included block in extended template

### ISSUE THREAD

**Issue by pun-ky** [fenom-template/fenom#191]
I have following situation

A.tpl
```
{include 'A/header.tpl'}
```

A/header.tpl
```
{block 'header'}
    {if Auth::logged()}
       {include 'A/main-menu.tpl'}
    {/if}
{/block}
```

A/main-menu.tpl
```
{block 'main-menu'}menu from A{/block}
````

In other module, which is extending my CMS, I wanna have:

B.tpl

```
{extends 'A.tpl'}

{block 'main-menu'}I wanna override by menu from B{/block}
```

But 'main-menu' cannot be overidden from B.tpl . No error at all. How to solve this? However when I place 'main-menu' block directly on A.tpl everything work properly (but is not expected in that case).

This feature is critical for using Fenom in my application. I've already migrated most of my templates to Fenom without any problems but this looks for me like a real blocker.

**Comment by bzick** [comment]
This behavior is correct. The blocks compiled at compile time template when there are no variables and values. Because inheritance in templates like class inheritance in PHP, you can't change parent using condition or values. Fenom sees it like that:

```php

class A {}

class header {
	public function header() {
		if(Auth::logged()) {
			new mainMenu();
		}
	}	
}

class MainMenu {
	public function mainMenu() {/* ... */}	
}

class B extends A {
	public function mainMenu() {/* ... */} // this is method doesn't redefine MainMenu::mainMenu() method
}

```

What I want to say that all the blocks that can be overridden must be explicitly specified in the parent template.

**Comment by bzick** [comment]
Fenom supports template name as array:
```
$fenom->fetch(["child1.tpl", "child2.tpl", "layout.tpl"], $data);
$fenom->display(["child1.tpl", "child2.tpl", "layout.tpl"], $data)
```
there child1.tpl extends child2.tpl extends layout.tpl. You may combine some blocks from PHP using this method

**Comment by pun-ky** [comment]
Your assumptions about template inheritance looks good / comparison to class inheritance seems to be logic. I agree. I am just doing a migration and I wanna say that in Laravel's Blade template engine that was possible, so if you are open and the problem is realizable in rational time maybe it is a good point to add such improvement?

**Comment by pun-ky** [comment]
I replaced include tag calls with copy pasted inline code and everything works so I rate this as dysfunction. Now I have a problem, because I cannot imagine rational workaround for it.

**Comment by pun-ky** [comment]
"you can't change parent using condition or values." I totally disagree. After that I replace include calls with copy pasted template content everything works...

**Comment by bzick** [comment]
The issue is still actual?
