### ISSUE TITLE
Поддержка стандартным провайдером PHAR #bug

### ISSUE THREAD

**Issue by rednakse** [fenom-template/fenom#192]
Из-за поддержки функцией [realpath](http://php.net/manual/ru/function.realpath.php) только протокола "file://" (по крайнем мере в 5.4) оказалось невозможным запаковать шаблоны в архив PHAR. [Исправлено](https://github.com/rednakse/fenom/commit/8d7ed4e143dca72e5dae27f84546a57ad0e73be3).

**Comment by bzick** [comment]
Все решается отдельным своим источником. То что примитивный источник шлабона работает с FS так и задумано. Вы сделали правильно, только надо создать свой Provider класс  и задайте его как основной источник:

```php
$fenom = new Fenom(new PharProvider($template_dir));
```
