### ISSUE TITLE
Шаблон не перекомпилируется

### ISSUE THREAD

**Issue by Awilum** [fenom-template/fenom#193]
Основной шаблон layout.tpl

...
<div id="wrap">
    {insert 'navbar.tpl'}
</div>
...

любые изменения в navbar.tpl не попадают в скомпилированный шаблон, пока не включить опцию force_compile в true

есть ли возможности как-то это исправить ? другие опции на это могут повлиять, чтобы не влючать force_compile ?

**Comment by pafnuty** [comment]
Используйте `{include}`.
`{insert}` вставляет код включаемого шаблона в родительский, поэтому шаблон не компилится.
Это сделано для увеличения производительности.
Я в качестве лайфхака просто пересохраняю родительский шаблон или на время разработки отключаю кеширование.

P.S. Подозреваю, что интеграция фенома в морфи идёт? Могу помочь, чем смогу. Видел ссылку на коммит, но в репозитории так его и не нашёл.

**Comment by Awilum** [comment]
>на время разработки отключаю кеширование.
Я так и сделал, то это немного неудобный вариант. попробую include, спасибо

>Подозреваю, что интеграция фенома в морфи идёт
да, но я не принял ваш пул реквест. так как, там много всего и сразу. Я разбил на задачи и просматривая ваш код внедрял его в морфи, но немного иначе. Сейчас делаю новый офф.сайт для морфи к релизу 1.1.0 на этом движке fenom. в milestones тикеты которые идут в релиз.

**Comment by pafnuty** [comment]
> да, но я не принял ваш пул реквест. так как, там много всего и сразу.

Да, я так и понял, не нужно было форматировать код, да и комментарии не помешали бы с пояснениями по коду.
В следующий раз постараюсь не так радикально подходить к коду.
