### ISSUE TITLE
Ошибка с классом Provider

### ISSUE THREAD

**Issue by alekseylovchikov** [fenom-template/fenom#194]
Приветствую!

Не могу корректно подключить Fenom в проект.

Ниже код подключения:

require_once "vendor/autoload.php";
Fenom::registerAutoload();

$options = array(
    "auto_reload" => true,
    "force_include" => true
);

$fenom = new Fenom(new Provider(__DIR__ . 'templates/to/template'));
$fenom->setCompileDir(__DIR__ . 'templates/to/template/cache');
$fenom->setOptions($options);

Выводит ошибку:
Fatal error: Class 'Provider' not found

**Comment by maxicms** [comment]
Если вы используете composer autoloader то нет нужды в этом коде 
```
Fenom::registerAutoload();
```

**Comment by alekseylovchikov** [comment]
Хорошо, но проблема по прежнему актуальна.

**Comment by rednakse** [comment]
namespace?
 use Fenom\Provider
 $fenom = new Fenom(new Provider(DIR . 'templates/to/template'));
или
 $fenom = new Fenom(new Fenom\Provider(DIR . 'templates/to/template'));

**Comment by bzick** [comment]
Если Вы используете composer то автозагурзчик `Fenom::registerAutoload();` не обязательно подключать, composer знает как работать с Fenom.
@rednakse предложил правильное решение, в доке опущено namespace Fenom для элементов шаблонизватора
