### ISSUE TITLE
setOptions strip = true

### ISSUE THREAD

**Issue by soulcreate** [fenom-template/fenom#195]
при указании настройки strip = true
в следующий код
```
<?xml version="1.0"?>
```
вставляется ненужный пробел, который мешает разбору xml, в результате получается вот так:
```
< ?xml version="1.0"?>
```

**Comment by bzick** [comment]
Не корректно работала система защиты от инъекций PHP  в шаблон (тег <? ) при включенном strip. Исправлено в #2.8.2

**Comment by soulcreate** [comment]
Опция работает черезчур хорошо - вырезает необходимые пробелы из url адреса изображений.
К примеру вот из такой конструкции:
```
<img src="{$url_src}">
```
если переменная {$url_src} содержит два последовательных пробела, то они сольются в один.
PS: возможно такое происходит при повторном парсинге уже спарсенного шаблона. Все происходит внутри CMS MODX, и в терминах MODX - это чанк внутри шаблона.

**Comment by rednakse** [comment]
> вырезает необходимые пробелы из url адреса изображений
Что делают пробелы в url? Почему они не кодированы плюсом или "%20"?

**Comment by soulcreate** [comment]
URL картинки берется из базы данных, там они хранятся в исходном виде, "как есть".

**Comment by aios** [comment]
URL на картинки должны генерироваться исходя хранилища, имени проекта, даты, сущность. Если это не делается сразу - а скажем  доступно пользователю - то нужно делать пре-обработку контента в котором эти ссылки содержаться. @soulcreate

**Comment by rednakse** [comment]
Странно все это, не ошибка ли где-то в логике приложения? Как костыль можно использовать что-то вроде этого:

```php
	function my_urlencode($url) {
		return implode('/', array_map('urlencode', explode('/', $url)));
	}

	$url = '/my/plain  path/    to    image.jpg';

	print my_urlencode($url); // /my/plain++++++path/++++to++++image.jpg

	$fenom->addModifier('my_urlencode', function($url) {
		return implode('/', array_map('urlencode', explode('/', $url)));
	});

	/*
		{set $url_src = '/my/plain  path/    to    image.jpg'}
		<img src="{$url_src|my_urlencode}" alt="">
	 */
```

В другом случае есть тег `raw`, он не даст удалить пробелы, но, повторюсь, в url пробелы должны кодироваться.

```
	<img src="{raw $url_src}">
```
