### ISSUE TITLE
assign() - аналог есть ?

### ISSUE THREAD

**Issue by Awilum** [fenom-template/fenom#196]
Есть ли аналог http://www.smarty.net/docsv2/ru/api.assign.tpl ?

**Comment by maxicms** [comment]
Есть но не в ядре, нужно ставить расширение оно тут https://github.com/fenom-template/storage имеет смысл использовать это дополнение и возможность автоматической загрузки расширении  для фенома https://github.com/fenom-template/entity-loader

**Comment by bzick** [comment]
Да, есть дополнительным аддоном — https://github.com/fenom-template/storage
