### ISSUE TITLE
Загрузка шаблонов из нескольких директорий

### ISSUE THREAD

**Issue by Awilum** [fenom-template/fenom#199]
При инициализации или после инциализации, возможно ли указать другие директории шаблонов ?

```php
$fenom = Fenom::factory( template_dir_1 , template_dir_2, template_dir_etc   );
```

как это у Twig
```php
$loader->addPath($templateDir3);
```

Или мне указывать "рутовую" директорию при инициализации, для решения такой задачи ?

**Comment by Sleuthhound** [comment]
Не достаточно дополнительных источников шаблонов?
https://github.com/fenom-template/fenom/blob/master/docs/ru/ext/extend.md#Источники-шаблонов

```php
$fenom->addProvider("test", new Template\Provider(__DIR__));
$fenom->display("test:template.tpl", $vars);
{include "test:template.tpl"}
```

**Comment by bzick** [comment]
То что вам надо реализовано отдельным источником шалонов с поддержкой множества директорий где могут лежать шаблоны:
https://github.com/fenom-template/providers-collection#multi-directories-template-provider
