### ISSUE TITLE
Подцветка синтаксиса в PHPStorm (IDEA)

### ISSUE THREAD

**Issue by eugene20237** [fenom-template/fenom#200]
Большое количество разработчиков на PHP используют в своей практике среду разработки PHPStorm. На сегодняшний день я считаю её самой вменяемой IDE под PHP. Единственная проблема для меня - нет корректной проверки синтаксиса Fenom. Т.е. подцветка и обработка Inspections. Было бы здорово создать плагин для PHPStorm для поддержки Fenom.

P.S.: Может быть сам когда-нибудь сделаю, если будет время...

**Comment by bzick** [comment]
Я уже думал об этом, там надо знание  java, что останавливает

**Comment by virdignus** [comment]
я вот это нашёл, частично работает
https://github.com/klkvsk/fenom-phpstorm-plugin

**Comment by eugene20237** [comment]
Спасибо за ссылку!

**Comment by Grawl** [comment]
чот он не работает
