### ISSUE TITLE
Banchmark - актуальный ?

### ISSUE THREAD

**Issue by Awilum** [fenom-template/fenom#201]
На сколько актульны результаты Banchmark-а тут ?
Как я вижу, тут сравнивается первая версия Fenom, а вторая ?
https://github.com/fenom-template/fenom/blob/master/docs/en/benchmark.md

**Comment by pafnuty** [comment]
Сейчас попробовал запустить, 
![cmd admin](https://cloud.githubusercontent.com/assets/1635679/11720575/d42dec1a-9f70-11e5-8db8-211dcd54a847.png)
наверняка проблема легко решается, но я нагуглить не смог :(

**Comment by bzick** [comment]
benchmark был  удален из репозитория fenom и сброшен в https://github.com/fenom-template/benchmark. Именно сброшен, так как адаптировать под отдельный репозиторий у меня не хватило времени.  Раз о нем вспомнили то пожалуй займусь его воскрешением

**Comment by Awilum** [comment]
@bzick я Fenom использую для Morfy - https://github.com/morfy-cms/morfy и нехватает вот этого https://github.com/fenom-template/fenom/issues/199

**Comment by Sleuthhound** [comment]
https://github.com/fenom-template/fenom/issues/199#issuecomment-163967607

**Comment by maxicms** [comment]
Бенчмарк обновлен до актуальных версии.
