### ISSUE TITLE
Парсить с переменной 

### ISSUE THREAD

**Issue by demortx** [fenom-template/fenom#204]
С бд тяну шаблон почтового письма, и нужно его парсить, как я могу передать переменную в феном чтоб взаимодействовать с ним например в fetch?

**Comment by pafnuty** [comment]
Читали про [источники шаблонов](https://github.com/fenom-template/fenom/blob/master/docs/ru/ext/extend.md#%D0%98%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8-%D1%88%D0%B0%D0%B1%D0%BB%D0%BE%D0%BD%D0%BE%D0%B2)?

**Comment by demortx** [comment]
Представим конструкцию 
   ........
$str = 'Hi {$name}!';


$tpl =  $fenom->fetch( $str , array(
                    "name" => 'John',
                ));

Вот так думаю будет информативнее.

**Comment by aios** [comment]
А что если сделать это не до, а в процессе парсинга шаблонов? - добавить тег - к нему обработчик. Я бы так сделал. По крайней мере расширения вам в любом случае придется коснуться.

**Comment by demortx** [comment]
Не совсем вас понял, вряд ли осилю расширения

**Comment by pafnuty** [comment]
Что то типа этого
```
class DbProvider implements Fenom\ProviderInterface {
    // ...
getHiName () {
return 'Hi {$name}!'
}
}
```
```
$provider = new DbProvider();
$fenom->setProvider("db", $provider, "/tmp/cached/db");
```

`$fenom->display("db:hiname.tpl", $vars);`
