### ISSUE TITLE
Аналог register_function / register_modifier

### ISSUE THREAD

**Issue by youngvan** [fenom-template/fenom#205]
Есть ли он в fenom и можно ли его реализовать?

**Comment by aios** [comment]
Документацию читали?

**Comment by aios** [comment]
https://github.com/fenom-template/fenom/blob/master/docs/ru/ext/extend.md#Добавление-модификаторов

**Comment by youngvan** [comment]
как-то с ней не очень ок

Существует более простой способ добавления произвольной функции:
$fenom->addFunctionSmarty(string $function_name, callable $callback);

но вот функции такой я не вижу

**Comment by youngvan** [comment]
нашел, без addFunctionSmarty в конце
