### ISSUE TITLE
Запрашивание функции

### ISSUE THREAD

**Issue by No0k** [fenom-template/fenom#206]
Добавил функцию:
$fenom->addFunction('avatar', function ($variable) {
    return Users::user_avatar($variable);
});
Вызываю в шаблоне:
 {avatar($user.id)}
Получаю ошибку: 
Fatal error: Uncaught exception 'Exception' with message 'Function avatar not found' in C:\OpenServer\domains\tw\engine\classes\Fenom\Template.php:806 Stack trace: #0

**Comment by pafnuty** [comment]
`{$user.id|avatar}`
И используйте выделение кода :smile:

**Comment by pafnuty** [comment]
Пардон, перепутал с модификатором.
`{avatar variable=$user.id}`

```
$fenom->addFunction('avatar', function ($variable) {
	return Users::user_avatar($variable);
});
```
