### ISSUE TITLE
Yii2 "use" in template 

### ISSUE THREAD

**Issue by slims1988** [fenom-template/fenom#207]
{use yii\widgets\ActiveForm} или {use yii\widgets\ActiveForm as AF}

How to make this work?

**Comment by bzick** [comment]
```smarty
{use 'yii\widgets\ActiveForm.tpl'}
```

**Comment by pafnuty** [comment]
:smile: мне одному показалось странным слово `или` ?

**Comment by aios** [comment]
;) это норма

**Comment by slims1988** [comment]
**2pafnuty** Нет, я начал сначала писать на русском, потом подумал может кто ответит на английском.

**2bzick** мне нужно не загружать шаблон, а загрузить  "use yii\widgets\ActiveForm;" в шаблон php кодом что бы активировать форму в Yii2. Так как без нее выдает ошибку.
`Method ActiveForm::begin doesn't exist in \main\login.tpl`

**Comment by pafnuty** [comment]
@slims1988 вероятно стоит написать `use yii\widgets\ActiveForm as AF`
в php файле, а в шаблоне уже использовать:
`{AF::begin}`

**Comment by slims1988** [comment]
Я уже так пробовал сделать, вот что выходит http://f6.s.qip.ru/11k2tYxyX.png

**Comment by slims1988** [comment]
Так вариантов нет ?

**Comment by pafnuty** [comment]
Ну для начала хорошо бы привести код шаблона.
По скриншоту видно, что вы забыли как определять переменные в шаблоне.
`{set $form = AF::begin($userId)}`

**Comment by pafnuty** [comment]
> Вариант написания в файле точно не работает

Если не работает, значит неправильно передаёте что-то.

**Comment by slims1988** [comment]
http://pastebin.com/tE8B7ejD - вот код.

{var $form = yii\widgets\ActiveForm::begin(

**Comment by pafnuty** [comment]
@slims1988 не совсем понимаю для чего в шаблоне формировать массив, это же можно и нужно делать в логике работы приложения. 
Сформируйте необходимый массив данных в скрипте и в шаблоне выводите эти данные.

**Comment by bzick** [comment]
@pafnuty мне недавно пришлось сформировать массив в шаблоне, где ключ - статус объекта, а значение — css класс. CSS классы не мог назвать как статусы так как эти классы принадлежат бутстрапу. Получается этот массив просто часть самого шаблона и не может быть вынесен из него.

**Comment by pafnuty** [comment]
@bzick Поэтому и написал, что не совсем понимаю. 
Ведь по сути на примере всего лишь форма авторизации. 
Возможно есть весомые причины делать так как сделано или у Yii есть какие то ограничения в этом плане?

**Comment by slims1988** [comment]
@pafnuty В  Yii2 почти все загружается через пространство имен
Мне проще 1 раз в начале шаблона написать
```
use api\models\LoginForm;
use yii\helpers\Html;
```

И дальше в шаблоне уже использовать к примеру:
```
{LoginForm::function()} 
{Html::url('/')}
```
Чем писать каждый раз
```
{api\models\LoginForm::function()}
{yii\helpers\Html::url('/')}

```
