### ISSUE TITLE
Отладка

### ISSUE THREAD

**Issue by Ivan-Baranov** [fenom-template/fenom#208]
Есть ли способ получить в исключении информацию о номере строки в исходном tpl файле?

E_NOTICE  Trying to get property of non-object - /vendor/Fenom/Template.php(462) : eval()'d code:118

**Comment by bzick** [comment]
Он должен был сохранить файл на фс со своим именем + соль.
А вообще код шаблона можно получить так
```php
$fenom->compile("some.tpl", false)->getTemplateCode();
// или
$fenom->compileCode('{$template} {$code} ...')->getTemplateCode();
```

**Comment by Ivan-Baranov** [comment]
Спасибо, помогло. Вызвал из обработчика ошибок.
