### ISSUE TITLE
Проблема в Template.php или у меня руки кривые?

### ISSUE THREAD

**Issue by rxlab** [fenom-template/fenom#213]
Простейший скрипт
```
<?php
require_once 'Fenom/Fenom.php';
\Fenom::registerAutoload();
$fenom = Fenom::factory('templates', 'templates/cache');
$fenom->setOptions(Fenom::AUTO_RELOAD);
$var = array('test' => 'Тест');
$fenom->display("login-index.tpl", $var);
?>
```
выдаёт это:
Fatal error: Undefined constant 'T_ABSTRACT' in /Fenom/Template.php on line 253

**Comment by DoubleG-RUS** [comment]
Видимо у вас версия php меньше 5.0.0. Если нет то версию и код шаблона `(оформленный)` в студию.

**Comment by rxlab** [comment]
Вот шаблон:
`From Template {$title}`
Вот сценарий (пути убрал):
```
<?php
        require_once 'Fenom.php';
        \Fenom::registerAutoload();

        $fenom = Fenom::factory('templates', 'templates/cache');
        $fenom->setOptions(Fenom::AUTO_RELOAD);
        $fenom->display("index.tpl", array(
                'title' => 'Проверка',
        ));
?>
```
Вот ответ сервера:
`Fatal error: Undefined constant 'T_ABSTRACT' in Fenom/Template.php on line 253`
Версия php 5.6.16
Ничего понять не могу.

**Comment by pafnuty** [comment]
А у вас расширение http://php.net/manual/en/book.tokenizer.php для php установлено?

**Comment by rxlab** [comment]
Точно! Установил, всё заработало. Спасибо! =)
