### ISSUE TITLE
lower и upper

### ISSUE THREAD

**Issue by MdbM** [fenom-template/fenom#216]
Привет!

Столкнулся с проблемой, что upper и lower не работают с русскими буквами.

Имеем такой пример:
```
{filter|strtolower} // он же lower
Тестовая Строка - strtolower
{/filter}

{filter|strtoupper} // он же upper
Тестовая Строка - strtoupper
{/filter}

{filter|mb_strtolower:'UTF-8'}
Тестовая Строка - mb_strtolower:'UTF-8'
{/filter}

{filter|mb_strtoupper:'UTF-8'}
Тестовая Строка - mb_strtoupper:'UTF-8'
{/filter}
```
Соответственно имеем такое на выходе:

> Тестовая Строка - strtolower
> Тестовая Строка - STRTOUPPER
> тестовая строка - mb_strtolower:'utf-8'
> ТЕСТОВАЯ СТРОКА - MB_STRTOUPPER:'UTF-8' 

Исходя из выше написанного предлагаю заменить использование strtolower($str)|strtoupper($str) в lower|upper на mb_strtolower($str, 'UTF-8')|mb_strtoupper($str, 'UTF-8') соответственно.

**Comment by bzick** [comment]
А если расширение mbstrings не установлено?

**Comment by MdbM** [comment]
Так-то да. Тогда беда. Но, наверное, ни разу не встречал подобной ситуации.
Если копаться в смарти, то там у них хитро и если нет одного, то отдается другое.
Я для себя свой модификатор сделал, не проблема. Но идею, все же, предложил.
Если подобное не планируется, тогда можно смело закрыть :)

**Comment by maxicms** [comment]
Сегодня проверил на 2.8.1 вот такой код 
```
{'строка upper'|upper}
```
и все сработало как нужно, хотя сделал отдельный бранч для фикса именно функции для mb_ если bzick понравится думаю будет в коробке. хотя мне не особо нравиться один момент в решении. :)

**Comment by bzick** [comment]
@maxicms github говорит что ветки идентичные, где смотреть-то?)

**Comment by maxicms** [comment]
Пока не пушил, не нравиться мне самому пока решение просто одни костыли получается меняем на другие. :) это не айс.

**Comment by rednakse** [comment]
Категорически против. В любом случае ничего не мешает сделать [перегрузку функций](http://php.net/manual/ru/mbstring.overload.php) в большинстве случаях.

**Comment by bzick** [comment]
Перегрузка функций не всегда несет пользу, например перегрузка функции strlen может начисто сломать парсеры, которые рассчитывать получить количество байт, а не символов

**Comment by rednakse** [comment]
@bzick всего лишь хотел сказать, что изменение предсказуемого поведения компонента может привести к неожиданным результатам, что в свою очередь может вылиться в приключения ежика в тумане в поисках что же такого случилось в новой версии компонента. Все кто работал с php и не только рано или поздно натыкались на подводные камни с i18n. Так же версии языка разные, модули для работы с муьтибайтом или iconv могут быть отключены, и даже может отсутствовать возможность их подключения. Далее, хоть все и стремится для работы с utf-8, другие кодировки все же никто не отменял пока. Конечно же это только мое мнение, но то что работает везде и универсально - ломать не стоит. Если хочется чтобы работало именно в этом проекте и именно с данным окружением - уже есть возможность в самом шаблонизаторе сделать свой модификатор, если это только для фронтэнда - css тоже никто не отменял, перегрузка понадобилась давно в одном проекте, и проблем не возникало, сейчас не знаю какая ситуация.

**Comment by rednakse** [comment]
```php
class Fenom
    public function __construct{
        Fenom\Modifier::$use_mbstring = extension_loaded('mbstring');
...

    protected $_modifiers = array(
        "upper"       => 'Fenom\Modifier::strtoupper',
        "up"          => 'Fenom\Modifier::strtoupper',
        "lower"       => 'Fenom\Modifier::strtolower',
        "low"         => 'Fenom\Modifier::strtolower',
...

class Modifier
{
	public static $mb_encoding = 'UTF-8';
	public static $use_mbstring;

    public static function strtoupper($str){
        return self::$use_mbstring ? mb_strtoupper($str, self::$mb_encoding) : strtoupper($str);
    }

    public static function strtolower($str){
        return self::$use_mbstring ? mb_strtolower($str, self::$mb_encoding) : strtolower($str);
    }
```

**Comment by bzick** [comment]
Если есть такая потребность (не не хотите/не можете перегрузить строковые функции) то просто переопределите модификаторы, 

```php
$this->fenom->addModifier('up', 'mb_strtoupper');
$this->fenom->addModifier('upper', 'mb_strtoupper');
$this->fenom->addModifier('low', 'mb_strtolower');
$this->fenom->addModifier('lower', 'mb_strtolower');
``` 

И тогда у Вас будет все штатно работать в шаблоне через встроенные модификаторы `up`  и `low`
