### ISSUE TITLE
Как передать модификатору строчку в одинарных кавычках?

### ISSUE THREAD

**Issue by soulcreate** [fenom-template/fenom#221]
Пытаюсь передать модификатору следующую конструкцию:
```
{$content|firstimg:'<img src="{$img}"'}
```
На что получаю ошибку:
```
Unexpected token <img in expression in ...
```
Что я делаю не так?

**Comment by pafnuty** [comment]
Попробуйте так:
``` smarty
{set $firstImg}
<img src="{$img}">
{set}
{$content|firstimg:$firstImg}
```

**Comment by bzick** [comment]
Сходу проблема не воспроизвелась. Какая версия  Fenom? Как вы вызываете этот код (в шаблоне или выполняете "на ходу" через compileCode)?

**Comment by soulcreate** [comment]
да тут я сам тупанул, извиняюсь за выражение
