### ISSUE TITLE
Unexpected token 'function' in expression

### ISSUE THREAD

**Issue by slims1988** [fenom-template/fenom#225]
> {yii\grid\GridView::widget([
'dataProvider' => $dataProvider,
'layout'=>"{items}",
'columns' => [
['class' => 'yii\grid\SerialColumn'],
'id',
['attribute' => 'title','value' => **function ($news) {return "['.$news[data][0][language].'] "".$news[data][0][title]";}**]
'published:ntext',
['class' => 'yii\grid\ActionColumn'],
],
'tableOptions' => ['class' => 'table table-bordered'],
])}

Выдает ошибку токена, как сделать что бы данная функция обрабатывалась??

**Comment by aios** [comment]
Обновить версию PHP

2016-05-07 15:50 GMT+03:00 slims1988 <notifications@github.com>:

> {yii\grid\GridView::widget([
> 'dataProvider' => $dataProvider,
> 'layout'=>"{items}",
> 'columns' => [
> ['class' => 'yii\grid\SerialColumn'],
> 'id',
> ['attribute' => 'title','value' => *function ($news) {return
> "['.$news[data][0][language].'] "".$news[data][0][title]";}*]
> 'published:ntext',
> ['class' => 'yii\grid\ActionColumn'],
> ],
> 'tableOptions' => ['class' => 'table table-bordered'],
> ])}
>
> Выдает ошибку токена, как сделать что бы данная функция обрабатывалась??
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/fenom-template/fenom/issues/225>
>



-- 
С уважением, Габриелян Д.М.

ICQ:      *3092095*
Skype:  *gt_fios*

**Comment by slims1988** [comment]
При чём тут версия php? Если данный код пропускать через обычный php файл, все отлично работает. А когда уже с использованием шаблонизатора то нет.

**Comment by pafnuty** [comment]
php код и не должен работать в шаблонизаторе.
Формируйте массив с данными на стороне php и обрабатывайте данные в шаблоне - это самый правильный вариант.
Либо сделайте свой модификатор и обрабатывайте данные в шаблоне через него.

**Comment by aios** [comment]
А я уж думал - он просто анонимные функции запускает где не попадя)

7 мая 2016 г., 18:03 пользователь Pavel Belousov <notifications@github.com>
написал:

> php код и не должен работать в шаблонизаторе.
> Формируйте массив с данными на стороне php и обрабатывайте данные в
> шаблоне - это самый правильный вариант.
> Либо сделайте свой модификатор и обрабатывайте данные в шаблоне через него.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/fenom-template/fenom/issues/225#issuecomment-217642983>
>



-- 
С уважением, Габриелян Д.М.

ICQ:      *3092095*
Skype:  *gt_fios*

**Comment by slims1988** [comment]
@pafnuty спасибо, сразу чет не сообразил что бы собирать массив в контроллере.
Проблема можно считать решена.
