### ISSUE TITLE
Операции над переменными без отображения

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#228]
Подскажите, как реализовать операции над переменными без отображения, например:
{$count++}, {$object->method()}

Сейчас решаю у себя таким образом, что конечно не совсем красиво:
{set $tmp = $count++}, {set $tmp = $object->method()}

**Comment by bzick** [comment]
Да, давно напрашивается тег `do`. Теперь (с 2.10.0) можно писать

```smarty
{do $count++}
{do $object->method()}
```

Выполнит без отображения результата на экране
