### ISSUE TITLE
Глобальные переменные, доступные для модификации

### ISSUE THREAD

**Issue by Sleuthhound** [fenom-template/fenom#230]
Плавно назревает вопрос, можно ли для определенных глобальных переменных добавить возможность изменения значений. Например $.session. Конечно хорошо, что я могу в шаблонах получить значения, но часто возникает потребность, в процессе, модифицировать значение. Например присвоить $.session[чего-то там] = [какое то значение].

**Comment by maxicms** [comment]
Могу сказать только одно если возникает такая потребность, но ошибка в логике работы вашего приложения, и кода. менять глобальные переменные в шаблоне, это как выстрелить себе в глаз пытаясь понять где пуля.

**Comment by Sleuthhound** [comment]
Ну я говорю не все, а определенные. Причем не саму переменную, а определенные значения в массиве. У меня просто часть логики отрабатывает в шаблоне, плохо это или хорошо, но мне так удобнее.

**Comment by pafnuty** [comment]
Пробовали использовать модификаторы для этой цели?
Что то типа:
```smarty
{$.seeeion.foo|changeValue:'newValue'}
```

**Comment by Sleuthhound** [comment]
Нет, не пробовал. Но мне кажется, что не получится, так как вроде бы у глобальных переменных каждый раз происходит проверка на существование:
(isset($_SESSION['foo']) ? $_SESSION['foo'] : null)

**Comment by maxicms** [comment]
> Нет, не пробовал. Но мне кажется, что не получится, так как, вроде бы, у глобальных переменных каждый раз происходит проверка на существование:

Ну так проверка идет на наличие того есть переменная или нет чтобы передать в функции значение или null ну если вставить переменной значение то оно присвоится. Модификаторы будут работать нормально.

**Comment by Sleuthhound** [comment]
Пробуем:
```php
    ->addModifier('change', function ($item, $value) {
        var_dump($item, $value);
    });
```
Вызываем:
```smarty
{do $.session|change:'10'}
{do $.session.test|change:'10'}
```
На выходе получаем:
`
array(0) {}
string(2) "10"
NULL
string(2) "10"
`
Получается мы не знаем какую переменную надо модифицировать, имеем только переданное значение и значение самой переменной.

**Comment by maxicms** [comment]
ну не кто не мешает сделать
```
{$.session.test|change:test:10}
```

Да получается некоторая избыточность, но если учесть что это частные случай когда нужно менять глобальные переменные в шаблоне это куда удобнее чем писать велосипед.

**Comment by bzick** [comment]
@Sleuthhound ваша задача решается просто, если вам нужно что бы можно было писать в глобальную переменную то вам надо определить это:

```php
$this->fenom->addAccessorSmart('session', '$_SESSION', \Fenom::ACCESSOR_VAR);
```
Второй аргумент - PHP код который будет вставлен вместо акцессора. Так что методы там прописывать нельзя - будет фаталка

**Comment by bzick** [comment]
`\Fenom::ACCESSOR_VAR` - говорит парсеру что второй аргумент - переменная, так что в нее можно писать

**Comment by Sleuthhound** [comment]
Спасибо, свой костыль убрал). Не додумался переопределить.
