### ISSUE TITLE
Парсинг массива, записанного на php

### ISSUE THREAD

**Issue by soulcreate** [fenom-template/fenom#236]
Можно ли с помощью fenom распарсить следующую строчку, преобразовав её в массив?
```
[
'key' 	=> 'val',
'key2'	=> 'val2',
'key3'	=> 'val3'
]
```
т.е. строчка дана в виде `$string` переменной (как часть шаблона сайта, подтягивается из базы данных), хотелось бы преобразовать её в ассоциативный массив средствами fenom. Подскажите в каком направлении копать.
не хотелось бы для этого использовать `eval($php_code)`

**Comment by maxicms** [comment]
без eval не обойдется, феном не даст ничего кроме как модификатор который вы можете написать но опять же в нем будет ваш eval($code);

**Comment by soulcreate** [comment]
Ага, [вижу](https://github.com/fenom-template/fenom/blob/48f42c82a91dd35ccb019787e58766b85e51c0fb/src/Fenom/Template.php#L462), т.е. в результате все равно даже в fenom запускается eval.
А можно как-то валидацию произвести через fenom, прежде чем отправлять код в eval?
знаю, что к примеру в fenom вот такой код будет валидным, а в php - нет. (пропущены запятые)
```
[
'key'   => 'val'
'key2'  => 'val2'
'key3'  => 'val3'
]
```

**Comment by bzick** [comment]
eval вызывается только при первой компиляции, далее используется  include кеша

**Comment by bzick** [comment]
Нативно шаблонизатор таким не занимается. Но вы можете научить шаблонизатор парсить строки как вам угодно, например через можификатор

```php
$fenom->addModifier("parse_array", function ($code) {
	return eval("<?php return ".$code); // но я бы порекоментовал не использовать eval,
	// а передавать строку, например, в виде JSON.
});
```
далее в шаблне

```smarty
{set $data = $array_string|parse_array}
... используете $data как массив
```
