### ISSUE TITLE
Fenom JS

### ISSUE THREAD

**Issue by mes01** [fenom-template/fenom#240]
Планируется ли релиз Fenom на JS?

**Comment by bzick** [comment]
Вообще хотелось бы. Сейчас пока в поисках удобного токенайзера, либо придется писать, что затянет еще надолго. Если знаете какие-либо токенайзеры на js скидывайте сюда

**Comment by pafnuty** [comment]
А действительно ли нужен fenom на JS? 
Я, признаться не вижу особой выгоды перед другими популярными шаблонизаторами на js.
Разве что в качестве демонстрации возможностей или демок...

**Comment by maxicms** [comment]
Тоже думал над этим не смог придумать даже имперический проект в котором это бы пригодилось.

**Comment by mes01** [comment]
круто это в том случае если что шаблоны были бы универсальны(то есть один синтаксис) что для бэкэнда что для фронтенда. Можно рендерить страницу либо на клиенте либо на сервере, это же удобно.

**Comment by pafnuty** [comment]
@mes01 это возможно только в том случае — когда на фронте и на бэке используется один ЯП. Получается что бэк должен работать так же на js.

**Comment by EMDM45** [comment]
> @mes01 это возможно только в том случае — когда на фронте и на бэке используется один ЯП. Получается что бэк должен работать так же на js.

А как одно другому мешает? Взять, условный, **Handlebars** и переписать его под синтаксис Fenom. Т.е. вместо {{var}} пишем {$var} и так далее. Соответственно один и тот же файл-шаблон мы можем использовать и на сервере, и на клиенте... Разве нет?

**Comment by pafnuty** [comment]
В целом да, вы правы относительно изначальной темы вопроса, но с того времени прошло уже 6 лет :) 
За это время появилось очень много более эффективных способов реализовать шаблонизацию на JS, react, vue, svelte, а в ряде случаев бэкенд на nodejs имеет значительные преимущества по сравнению с php, в т.ч. единый синтаксис на бэке и фронте.
