### ISSUE TITLE
Что с переменными?

### ISSUE THREAD

**Issue by maiskiykot** [fenom-template/fenom#242]
Как ни странно, fenom не понимает элементарные переменные PHP вида $local.$url. Также не смог запустить конструкцию типа $val .= 'value'. Как быть?

**Comment by maxicms** [comment]
Можно более развернутый пример для чего использовать вот такую конструкцию 
```
$local.$url
```

если нужно вывести переменный то будет 
```
{$local}{$url}
```

по конструкции
```
  $val .= 'value'
```
будет вот так 
```
{set $val = $val + 'value'}
```

**Comment by maiskiykot** [comment]
Пример следующий - есть много уровней сайта, поэтому задается локаль - $local=http://www.ru, а $url - каталог или подкаталог сайта. Получается в пыхе - http://www.ru/catalogue/index.php. Fenom просто ругается на все способы и на $local.$url и на {$local}{$url}. Может его $local пугает?

**Comment by maxicms** [comment]
ну так все правильно чтобы вывести в шаблоне путь нужно просто написать 
```
<a href="{$local}/{$url}">тут ссылка</a>
```
при этом нужно просто передать значение данных переменных в fenom

**Comment by maiskiykot** [comment]
У меня переменная $local применяется повсеместно и в шаблонах и в пыхе. Не хотелось бы слеш из нее выкидывать. К тому же я вообще часто применяю конструкции $var1.$var2.$var3 - а тут проблема именно в их интерпретации fenom-ом.

**Comment by maiskiykot** [comment]
{set $val = $val + 'value'} - это выдает 0

**Comment by maxicms** [comment]
тут я не сразу понял, для строковых выражении нужно использовать строковые операторы
```
$a ~ $b - возвращает результат объединения сток $a и $b
$a ~~ $b - возвращает результат объединения сток $a и $b через пробел
$a ~= $b - присвоение с объединением
```

**Comment by maiskiykot** [comment]
Сработало! Спасибо!

**Comment by maiskiykot** [comment]
Если можно, то как добиться работы конструкции $val  .= 'value'?

**Comment by bzick** [comment]
@maiskiykot точка уже зарезервирована под отображение к элементам, для конкатинации используйте тильду: `$val ~= 'value'` (то же что и а PHP `$val .= 'value'`)
