### ISSUE TITLE
Что за новый оператор "??"?

### ISSUE THREAD

**Issue by DaaGER** [fenom-template/fenom#243]
В changelog "Added ?? operator", но нигде не могу найти описание этого оператора. В коммитах тоже не нахожу ничего, куда смотреть?

**Comment by bzick** [comment]
Оператор аналогичен оператору `??`(Null Coalescing Operator) в php http://php.net/manual/en/language.operators.comparison.php#language.operators.comparison.coalesce
В доке пока не упоминается так как на него нет тестов. Пока не добавлю тесты лучше его не использовать

**Comment by bzick** [comment]
По сути это тот же `?:` только с проверкой существования переменной, не зависимо установлена опция FORCE_VERIFY

**Comment by DaaGER** [comment]
Спасибо за ответ и fenom.

**Comment by bzick** [comment]
Всегда пожалуйста
