### ISSUE TITLE
Можно ли записать результат функции в переменную?

### ISSUE THREAD

**Issue by hashstudio** [fenom-template/fenom#250]
Задача: перебрать массив, полученный из функции.

**Comment by hashstudio** [comment]
Данную проблему можно решить вот так:

```php
$fenom->addAccessorSmart($name, $callable, Fenom::ACCESSOR_CALL);
```

Вопрос с обычными функциями - совсем никак не добиться записи в переменную?

**Comment by bzick** [comment]
Вам поможет [системная переменная](https://github.com/fenom-template/fenom/blob/master/docs/ru/syntax.md#%D0%A1%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%BD%D0%B0%D1%8F-%D0%BF%D0%B5%D1%80%D0%B5%D0%BC%D0%B5%D0%BD%D0%BD%D0%B0%D1%8F) `$.call` 
```smarty
{set $data = $.call.php_function($x, $y)}
```
