### ISSUE TITLE
Из шаблона, добавленного extends, не подтягиваются зависимости

### ISSUE THREAD

**Issue by irbisoff** [fenom-template/fenom#252]
Массив depends не заполняется дальнейшими зависимостями из родительского шаблона.

Также, довольно проблематично добавить собственную зависимость (например, при использовании js/css компилятора): для addDepend нужно передавать Fenom\Render, который является большим оверхедом при известном имени и mtime файла зависимости.

Решение: http://img.access.to/1dJFR

**Comment by irbisoff** [comment]
`diff --git a/src/Fenom/Template.php b/src/Fenom/Template.php
index 9a5b449..9a1c3f9 100644
--- a/src/Fenom/Template.php
+++ b/src/Fenom/Template.php
@@ -492,7 +492,33 @@ class Template extends Render
      */
     public function addDepend(Render $tpl)
     {
-        $this->_depends[$tpl->getScm()][$tpl->getBaseName()] = $tpl->getTime();
+        $this->addRawDepend($tpl->getScm(), $tpl->getBaseName(), $tpl->getTime());
+
+        foreach ($tpl->getDepends() as $scm => $depends) {
+            foreach ($depends as $depend => $time) {
+                $this->addRawDepend($scm, $depend, $time);
+            }
+        }
+    }
+
+    /**
+     * Add depends without Render
+     * @param string $scm
+     * @param string $basename
+     * @param int $time
+     */
+    public function addRawDepend($scm, $basename, $time)
+    {
+        $this->_depends[$scm][$basename] = $time;
+    }
+
+    /**
+     * Get template depends
+     * @return array
+     */
+    public function getDepends()
+    {
+        return $this->_depends;
     }

     /**`

**Comment by bzick** [comment]
Вы хотите пересобирать шалблон при изменении  js/css?

**Comment by irbisoff** [comment]
Именно. Причин две:
1. Предотвращение клиентского кеширования css/js, добавляется mtime get-параметром.
2. Основной css, необходимый для первичной отрисовки страницы, вставляется инлайном. Остальной - в футере страницы, отдельными уже файлами, не блокируя отрисовку.

Но это только дополнительный функционал, впрочем. Основное - шаблон не пересобирается сейчас при изменении зависимостей из extends.

**Comment by bzick** [comment]
ttl expired
