### ISSUE TITLE
fenom vs smarty vs twig

### ISSUE THREAD

**Issue by aolko** [fenom-template/fenom#253]
Какой шаблонизатор лучше: fenom, smarty или twig?

**Comment by bzick** [comment]
Почему вы спрашиваете именно в репозитории fenom?

**Comment by aolko** [comment]
для создания шаблонов продакшн сайта, просто на данный момент я мигрирую со смарти

**Comment by maxicms** [comment]
Ну скорее всего не так нужно было спросить :) А как вы думаете какой вам дадут ответ на ваш вопрос, разработчики шаблонизатора. Конечно fenom круче :)))  Есть бранч с тестами, там все есть можете запустить и посмотреть.

**Comment by aolko** [comment]
лучше б запилили сравнение с твигом и смарти, было б нагляднее

**Comment by pafnuty** [comment]
@aolko Так ведь https://github.com/fenom-template/benchmark он и есть

**Comment by pafnuty** [comment]
Вообще лучше выбрать инструмент для решения конкретных задач.
Есть (почти всегда) ситуации, когда более богатая функциональность будет более выгодна, чем производительность или принятые в команде правила морально не позволяют использовать синтаксис какого-то шаблонизатора.
Очень много переменных, которые влияют на выбор шаблонизатора.

Для меня лично ключевым критерием являлась скорость работы и "отечественный продукт" а так же более привычный синтаксис.

Если вы мигрируете со смарти - выбирайте феном конечно же т.к. он будет привычнее, да и  [фолбэк](https://github.com/fenom-template/smarty-fallback) для смарти есть, используйте его и переезжайте потихоньку на феном.

**Comment by aolko** [comment]
под сравнением подразумевалось куски шаблонов в два столбца вставить и выделить в чём похожести и отличия

**Comment by maxicms** [comment]
Ну как писали выше если сравнивать эти шаблонизаторы то  smarty и fenom самые похожие примерно на 90% и переехать со смарти будет очень быстро.
