### ISSUE TITLE
switch space after case

### ISSUE THREAD

**Issue by soulcreate** [fenom-template/fenom#256]
Если не стоит пробела после конструкции `{case 22}` (после закрывающей фигурной скобки) то неправильно работает конструкция `{switch}`

**Comment by bzick** [comment]
Что подразумевается под "неправильно работает конструкция"?

**Comment by soulcreate** [comment]
"Съедает" часть открывающего за ней HTML тэга, а точнее открывающую скобку `<` и сам тэг, оставляя класс, текст и закрывающий тэг.

**Comment by bzick** [comment]
Действительно такой дефект присутствует

**Comment by bzick** [comment]
Исправлено в 2.11.5
