### ISSUE TITLE
Кэш $.get

### ISSUE THREAD

**Issue by aaa-artemius** [fenom-template/fenom#259]
Заметил что если использовать глобальный массив GET для фильтрации и обрабатывать формы с учетом значений GET параметров, то fenom кэширует  $.get. 
Пока не сбросишь системеый кэш, так и не изменится.
Может есть какая то фишка, чтобы не кэшировались глобальные массивы?

**Comment by bzick** [comment]
Феном не умеет кешировать, в обычном понимании. Как вы сбрасываете кеш?

**Comment by aaa-artemius** [comment]
В modx fenom идет в комплекте с дополнением pdoTools, в документации везде указано, что fenom не кэширует, но вчера словил такое.
В modx есть сброс системного кэша из админке.

**Comment by bzick** [comment]
А в чем выражается кеш?

**Comment by aaa-artemius** [comment]
Пример: есть форма в форме select с выбором для фильтрации. Выбираю отправляю форму. И после перезагрузки относительно get параметров хочу выделить в селекте выбранный пункт, но вот $.get показывает предыдущее значение. Даже после перезагрузок страниц значение старое. Только после сброса кэша, отображает новое значение.

**Comment by bzick** [comment]
То есть после перезагрузки страницы у вас старые значения в $.get, от предидущей страницы?

**Comment by aaa-artemius** [comment]
Да

**Comment by bzick** [comment]
Феном не может сделать такого, так как при обращении к `$.get` он обращается к `$_GET` на прямую, без какого-либо кеширования (смотреть [тут](https://github.com/fenom-template/fenom/blob/master/src/Fenom/Accessor.php#L20) и [тут](https://github.com/fenom-template/fenom/blob/master/src/Fenom/Accessor.php#L88)). По каким-то причинам у вас в системе `$_GET` кешируется либо был переопределён `$.get`. Рекомендую обратиться к разработчику **pdoTools**.

Так же убедитесь что у вас не кешируется сама страница в браузере и на сервере.

**Comment by aaa-artemius** [comment]
Страница не кэшируется так как данные то выдает правильно. 
Пойду к разработчику pdoTools.
Спасибо

**Comment by aaa-artemius** [comment]
Сорри, нашел косяк, вызвал сниппет без запрета на кэш.
Еще раз прошу прощения за беспокойство.)))
