### ISSUE TITLE
Массив в шаблон не работает

### ISSUE THREAD

**Issue by No0k** [fenom-template/fenom#265]
В доках описания не нашел.
Есть запрос:

```
<?php
$fraction = array();
$fraction = Vars::get('db')->query('SELECT `id`,`name` FROM `fraction` ORDER BY `member` ASC')->fetch_all();
Vars::get('fenom')->display('tutorial/step2.tpl', $fraction);
?>
```
Получается в шаблон я передаю такой массив: 
![image](https://cloud.githubusercontent.com/assets/9604811/22634377/c8e10202-ec31-11e6-9938-f235e096f7c6.png)
Но когда я его вызываю в шаблоне:
```
{foreach $fraction as $key => $value}
    {$key.id} - {$key.name}
{/foreach}
```
В ответ я получаю пустоту. Подскажите в чем ошибку допустил. Ведь я шаблон передал массив, а вызвать не могу.

**Comment by bzick** [comment]
Попробуйте так
```php
Vars::get('fenom')->display('tutorial/step2.tpl', ["fraction" => $fraction]);
```

Вы массив $fraction вбросили в глобальное пространство имен

**Comment by No0k** [comment]
> Вы массив $fraction вбросили в глобальное пространство имен
Немного Вас не понял.

**Comment by axules** [comment]
@No0k ,
у тебя в шаблон пришел не $fractial, а его "кишки".
если у меня будет `$a = {x: 10, y: 20, z: 30}`, 
я сделаю `Vars::get('fenom')->display('tutorial/step2.tpl', $a);`
то внутри шаблона у меня не будет `$a`,  а будут его поля - `$x, $y, $z`.
Если захочу `$a`, что сделаю `Vars::get('fenom')->display('tutorial/step2.tpl', [ 'myA'=> $a]);`
а в шаблоне буду юзать `$myA` и все будут счастливы =)

**Comment by bzick** [comment]
@axules полностью все описал
