### ISSUE TITLE
Мелкий косяк в модификаторе IN

### ISSUE THREAD

**Issue by tsukasa-mixer** [fenom-template/fenom#269]
```
{set $x = 3}
{set $a = [1, 2, 3, 5  42]}
{set $b = [5, 8, 13, 42]}
{if $x|in:$a}
    true
{/if}
{if $x|in:$b}
     true
{/if}
```
В обоих случаях будет выведено true
array_key_exists  - всеж лишний

https://github.com/fenom-template/fenom/blob/master/src/Fenom/Modifier.php#L175

**Comment by bzick** [comment]
Хорошо, уберу

**Comment by bzick** [comment]
однако вам стоит использовать [оператор присутствия](https://github.com/fenom-template/fenom/blob/master/docs/ru/operators.md#Оператор-присутствия):

```smarty
{if $x in list $b}
     true
{/if}
```

**Comment by bzick** [comment]
Хотя, если вдуматься, менять модификатор не стоит так как это нарушение обратной совместимости.  Тем более оператор присутствия полностью решает вашу задачу.

Однако я оставлю замечание в документации.

**Comment by tsukasa-mixer** [comment]
Принято - спасибо за подсказку.
