### ISSUE TITLE
Unexpected token $, isset() and empty() accept only variables

### ISSUE THREAD

**Issue by sunhaim** [fenom-template/fenom#272]
Получаю такую ошибку:
Fatal error: Uncaught exception 'Fenom\Error\TokenizeException' with message 'Unexpected token $, isset() and empty() accept only variables' in .../vendor/fenom/Fenom/Template.php:910

В коде подключаю свойство так:
```
$this->fenom->addAccessorSmart( 'page', 'page_data', Fenom::ACCESSOR_PROPERTY );
$this->fenom->page_data =[
   ...
];
```

В шаблоне простая проверка:
```
{if !empty( $.page.meta_keywords )}
   <meta name="keywords" content="{$.page.meta_keywords}">
{/if} 
```

**Comment by bzick** [comment]
Исрпвлено в 2.11.7

**Comment by bzick** [comment]
В вашем случае можно обойтись без empty. Fenom сам проверяет наличие переменно если включить force_verify

```smarty
{if $.page.meta_keywords}
   <meta name="keywords" content="{$.page.meta_keywords}">
{/if} 
```
