### ISSUE TITLE
include не находит шаблон если папка с шаблонами подключена как дополнительный источник шаблонов

### ISSUE THREAD

**Issue by z7zmey** [fenom-template/fenom#273]
есть папка `some_templates` с двумя шаблонами

`base.tpl`
```
{include "child.tpl"} 
```
`child.tpl`
```
{$helloWorld}
```

`$tpl->fetch('st:base.tpl');` выдает ошибку `Template child.tpl not found`
Ожидается что include будет искать шаблоны в той же папке в которой лежит базовый.

Папка `some_templates` используется в двух проектах. В одном в качестве основного источника шаблонов, во втором как дополнительный источник шаблонов.

**Comment by bzick** [comment]
что у вас за поставщик `st` ?
Если нужно что бы child.tpl был из того же потсавщика то надо указывать при include
```
{include "st:child.tpl"} 
```

**Comment by z7zmey** [comment]
Постовщик `st` добавляю таким образом 
```
$fenom->addProvider('st', new \Fenom\Provider('/some_templates/));
```
`{include "st:child.tpl"} ` приводит к тому что шаблон не грузится в основном проекте.

**Comment by z7zmey** [comment]
Хотелось бы иметь возможность написать несколько шаблонов которые будут расшарены на несколько проектов, при этом я не знаю и не должен знать, каким образом в проектах они будут подключаться.

так
```
$fenom = Fenom::factory('/some_templates/')
```
или так
```
$fenom = Fenom::factory('some_dir')
$fenom->addProvider('st', new \Fenom\Provider('/some_templates/));
```

**Comment by EMDM45** [comment]
> Постовщик `st` добавляю таким образом
> 
> ```
> $fenom->addProvider('st', new \Fenom\Provider('/some_templates/));
> ```
> 
> `{include "st:child.tpl"} ` приводит к тому что шаблон не грузится в основном проекте.

Не грузится, возможно потому, что нужно указывать полный путь, т.е. `$_SERVER['DOCUMENT_ROOT'].'/some_templates/'`. (в результате получается, например, `/www/some_templates/`

**Comment by z7zmey** [comment]
Не смог воспроизвести. Закрываю задачу.
