### ISSUE TITLE
Аналог array_chunk при использовании foreach

### ISSUE THREAD

**Issue by sartatpdev999** [fenom-template/fenom#275]
Есть ли из коробки способ разбить массив на части при использовании foreach? Без использования pdotools_fenom_php=true и array_chunk($array, $chunkSize) или введением дополнительных переменных. Что-нибудь сродни:
```
{foreach $array as $arrayChunk chunkSize=4}
  <div class="row">
  {foreach $arrayChunk as $key => $value}
    <div class="col-lg-3 col-md-3">
      Hi. I'm column #{$value}
    </div>
  {/foreach}
  </div>
{/foreach}
```
Или, может быть, есть какой-то способ проще?

**Comment by maxicms** [comment]
как вариант может быть такое решение 
```
{foreach $array as $key => $value}
   {cycle ['<div class="row">', '', '','']}
    <div class="col-lg-3 col-md-3">
      Hi. I'm column #{$value}
    </div>
  {cycle ['', '', '','</div>']}
{/foreach}

```

**Comment by bzick** [comment]
@sartatpdev999 вы почти правы, используйте [array_chunk](http://php.net/manual/ru/function.array-chunk.php)
```smarty
{foreach $array|array_chunk:4 as $arrayChunk}
  <div class="row">
  {foreach $arrayChunk as $key => $value}
    <div class="col-lg-3 col-md-3">
      Hi. I'm column #{$value}
    </div>
  {/foreach}
  </div>
{/foreach}
```

**Comment by bzick** [comment]
Или вы ограничены в использовании модификаторов?

**Comment by sartatpdev999** [comment]
А не работает без ```pdotools_fenom_php=true```

**Comment by bzick** [comment]
Я не знаком с pdotools. Какие еще ограничения на Fenom накладывает `pdotools_fenom_php=true`? Можно ли добавить свой модификатор в Fenom?

**Comment by sartatpdev999** [comment]
Я не знаю, я сам с ним недавно знаком. Да, оказывается можно. Попробовал по [мануалу](https://docs.modx.pro/components/pdotools/parser#%D0%A1%D0%BE%D0%B1%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5-%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B):
```
case 'pdoToolsOnFenomInit':
  $fenom->addModifier('array_chunk', function ($array, $chunkSize) {
    return array_chunk($array, $chunkSize);
  });
  break;
```
И по всей логике должно работать, но пока не работает. Но это уже другая тема. Спасибо!
