### ISSUE TITLE
codeigniter 3.x

### ISSUE THREAD

**Issue by demortx** [fenom-template/fenom#282]
Не одной документации как подключить его к codeigniter, может есть готовое решение?

**Comment by VasiliyUlasevich** [comment]
Примерно так (в корне проекта CodeIgniter):
composer require fenom/fenom

далее в application/config/config.php
правим  $config['composer_autoload'] = 'vendor/autoload.php'

и всё, далее используем fenom  как описано в документации fenom-а,
т.е. к примеру в конструкторе контроллера инициализируем fenom
$this->fenom = Fenom::factory($template_dir, $template_cache_dir, $options);
а в методе заместо 
    $this->load->view 
используем 
   $this->fenom->display("template/name.tpl", $vars);

**Comment by demortx** [comment]
Без него ни как не обойтись?

**Comment by VasiliyUlasevich** [comment]
Если имеется ввиду composer то это только для удобства,
никто не мешает скачать всё вручную

**Comment by demortx** [comment]
Где это можно сделать, я не пользовался не когда  компрессором

**Comment by VasiliyUlasevich** [comment]
Качаем с гитхаба феном, распаковываем (для примера) в корень сайта,

в application/config/config.php
правим обратно $config['composer_autoload']=false;

Для примера прям в файле application/config/config.php в самом конце добавляем:
require_once FCPATH.'fenom-master/src/Fenom.php';
Fenom::registerAutoload();

дальше используем как в ответе на первый коммент

**Comment by demortx** [comment]
Спасибо разобрался, правда вынес все в контролер!
