### ISSUE TITLE
Развитие проекта

### ISSUE THREAD

**Issue by etoseo** [fenom-template/fenom#288]
Думаю прикрутить к новому проекту. Вопрос будет ли шаблонизатор развиваться как-то или все.

**Comment by ZirionNeft** [comment]
Шаблонизатор топовый, как ни лучший - советую.

**Comment by maxicms** [comment]
На текущий момент проект живой и последние бенчмарки показывают его лидерство между другими шаблонизаторами. В скором времени будет оптимизация ядра так что стоит его использовать.

**Comment by etoseo** [comment]
Ок. Спасибо за ответы. Мне сразу приглянулся, остановило отсутствие обновлений. Но раз такое дело, возьму fenom, уж очень грамотно сделан.
