### ISSUE TITLE
Передача переменных в модификтор

### ISSUE THREAD

**Issue by soulcreate** [fenom-template/fenom#289]
Пытаюсь передать две строки, объединенные в одну, как параметр для модификатора:
```
{$var|modif:"const"~$str2}
```
в модификатор попадает только `const`.
если поэксперементировать так:
```
{set $param = "const"~$str2}
{$var|modif:$param}
```
то все работает как надо.
В чем я делаю ошибку?

**Comment by bzick** [comment]
Вопрос приоритета. У модификатора приоритет блольше бинарных опираций операций. Используйте скобки

```smarty
{$var|modif:("const"~$str2)}
```
