### ISSUE TITLE
Кэшированные файлы вдруг не могут записаться

### ISSUE THREAD

**Issue by DaaGER** [fenom-template/fenom#290]
В какой-то момент сайт падает с ошибкой, что fenom не может записать кэш и жалуется на права. Права на папку git:www-data 755, если папку для кэша очистить простым rm * всё сразу поднимается. Такое произошло второй раз и очень напрягает. Вроде как спасает не использование кэша, но такой вариант не очень нравится. Куда можно копать? Идеи?
Debian 7 & PHP 5.5.

**Comment by maxicms** [comment]
могу конечно ошибаться но разве не 777 должно быть на папку?
