### ISSUE TITLE
Использование $.php.Class::SomeFunction($x=123)

### ISSUE THREAD

**Issue by pooding55** [fenom-template/fenom#295]
Приветствую. Подскажите, пожалуйста, в доках сказано, что использовать `$.php.Class::SomeFunction($x=123)` не совсем корректно, да и php жалуется на DEPRECATED. Но как можно вызвать в шаблоне какой-либо метод? 
Например, в классе Core есть метод GetFenom (ниже код), а рядом с ним какой-нибудь GetMenu, например, которую нужно вызвать из шаблона. 

Вот так выглядит GetFenom
```php
public function GetFenom() {
    $fenom = Fenom::factory(ASSETS_PATH . 'templates', CORE_PATH . 'cache');

    $vars = array(
            'x' => 'Тут одно',
            'y' => 'Тут другое',
            'z' => 'Тут третье',
          );

    $fenom->display("/home.tpl", $vars);
  }
```

А вот так не работает: $_Core->GetMenu(), хоть и встречал такие записи...

**Comment by pafnuty** [comment]
@pooding55 
можно писать просто:
`{Class::SomeFunction($x=123)}`
либо завести тег:
```php 
$vars['menu'] = $_Core->GetMenu();
```
И использовать в шаблоне
```
{$menu}
```
