### ISSUE TITLE
Multiple Directory support for templates

### ISSUE THREAD

**Issue by physcocode** [fenom-template/fenom#298]
### I found this bug / would like to have this new functionality
I would like to have multiple directory for loading templates. Currently only a single directory is loaded by fenom

### This is Fenom and PHP version and environment (server/fpm/cli etc) I am using
PHP 7.1 FPM

**Comment by parkerj** [comment]
I think you need the [providers-collection](https://github.com/fenom-template/providers-collection).

**Comment by physcocode** [comment]
This is what I wanted thanks
