### ISSUE TITLE
Проблема с оператором in

### ISSUE THREAD

**Issue by RusWebBear** [fenom-template/fenom#306]
Пишу условие
`{if {$idx % 10} | in : [2, 3, 4, 5, 8, 9]}yes{/if}`
В результатах с 1 по 5 выдает `yes`, на 6 не выдает
Далее не смотрел поскольку у меня всего 6 элементов выводится

**Comment by bzick** [comment]
`{$idx % 10}` ? не помню что бы был такой синтаксис

**Comment by bzick** [comment]
Вы имели ввиду скобки `()` ?

**Comment by bzick** [comment]
попробуйте 
```smarty
{if ($idx % 10) in list [2, 3, 4, 5, 8, 9]}
yes
{/if}
```

**Comment by CrazyBoy49z** [comment]
Я думаю этот issue можно закрывать так как автор неверно его использовал
