### ISSUE TITLE
 Uncaught RuntimeException: Template 501.tpl not found 

### ISSUE THREAD

**Issue by Iti111** [fenom-template/fenom#307]
hi,
I am using your good template for a large project. 
const VERSION = '2.9';
    const REV = 1;
The only error I get is this one below. could you help me solve please?
9726#0: *3125407 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught RuntimeException: Template 501.tpl not found in ......................../php/lib/templater/vendor/Fenom/Provider.php:153
Stack trace:
#0 .....................php/lib/templater/vendor/Fenom/Provider.php(95): Fenom\Provider->_getTemplatePath('501.tpl')
#1 .............................php/lib/templater/vendor/Fenom/Template.php(182): Fenom\Provider->getSource('501.tpl', 0)
#2 ................................/lib/templater/vendor/Fenom.php(1108): Fenom\Template->load('501.tpl')
#3......................./php/lib/templater/vendor/Fenom.php(1067): Fenom->compile('501.tpl', true, 64)
#4 ...................................../php/lib/templater/vendor/Fenom.php(1021): Fenom->_load('501.tpl', 64)
#5............................./php/lib/templater/vendor/Fenom.php(962): Fenom->getTemplate('501.tpl')
#6 .............................../php/actions/co" while reading response header from upstream
```

**Comment by Iti111** [comment]
can anyone help? Server is debian 8. Apache with Nginx proxy.

**Comment by EMDM45** [comment]
> can anyone help? Server is debian 8. Apache with Nginx proxy.

How do you setup Fenom?
You must set `$template_dir`. And template dir must contain your tpl file 501.tpl.

**Comment by Iti111** [comment]
OK. Thanks. adding 501 to template dir solved it.
