### ISSUE TITLE
Не хватает одной важной штуки...

### ISSUE THREAD

**Issue by PavelBushalin** [fenom-template/fenom#319]
Привет
Сижу на SMARTY уже .... давно. Мне попался один проект с этим шаблонизатором. Все хорошо и быстро, но мне не хватает одной штуки.... а именно fetch из строки... я пытался сунуться в код, но там все пляшет от шаблона...  fetch("---STRING DATA---",$tplvar); 

В остальном все супер. Будет эта штука и SMARTY не нужен с его наворотами. Буду топить за FENOM. 

Заранее спасибо.

**Comment by demortx** [comment]
Да тоже поддерживаю, нужная функция сам не раз городил костыли чтоб это досадное ограничение обойти

**Comment by maxisoft-git** [comment]
А можете привести подробнее как вы хотите использовать это в шаблонизаторе?

**Comment by PavelBushalin** [comment]
приведу аналог из твига...
$this->TWIG->createTemplate($tplString)->render($tplArr);
бывают ситуации когда хочется обработать строку контроллером... сейчас для этого приходится делать сохранения строки в файл... возможно этот твигнутый аналог также делает сохранение... 
есть такое и у smarty....

**Comment by bzick** [comment]
Если вам не надо кешировать то достаточно выполнить это
```php
$result $fenom->compileCode($template_code)->fetch($vars);
```
в этом случае ничто никуда не будет сохранено (закешировано)
