### ISSUE TITLE
Release new version (also to Packagist / Composer)

### ISSUE THREAD

**Issue by alexroosenstein** [fenom-template/fenom#322]
Hi,

I'm using composer for most of my packages, including Fenom.

After recently setting up a new server with PHP 7.4 I got some errors in the Tokenizer class, which has already been fixed in 4dd1e1870cbeea6a39444dba8c6e74f9c8cb57c8 but unfortunately it's not pushed to Packagist yet.

Maybe you could do a new release, and push it to Packagist? Thanks

**Comment by bzick** [comment]
Done. https://github.com/fenom-template/fenom/releases/tag/2.12.0
