### ISSUE TITLE
обрабатывать var в унаследованных шаблонах

### ISSUE THREAD

**Issue by paw34rus** [fenom-template/fenom#79]
Сейчас из шаблона, наследующего другой шаблон, берутся только блоки. Было бы неплохо брать так же тег var, чтобы можно было менять значения переданных переменных. Например, в числе прочих передана переменная $title. Мы делаем {var $title = $title|upper}, этот код компилится и вставляется в начале сгенеренного шаблона. Получается некий аналог блоков, но часто удобнее работать именно с переменной.

**Comment by BTPAHCE** [comment]
Я поддерживаю необходимость данной функции. Уважаемый разработчик реализуйте пожалуйста данный функционал! Спасибо

**Comment by bzick** [comment]
Не воспроизводится. Если будет пример - скидывайте. Пока закрываю задачу
